/*
Edge Event Schemas

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package events

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AeAdvisoryRequestAssetDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AeAdvisoryRequestAssetDetail{}

// AeAdvisoryRequestAssetDetail Request to ask for advisory messages be produced for a particular asset(s)
type AeAdvisoryRequestAssetDetail struct {
	// Auction Edge unique identifier for an auction.
	AuctionId string `json:"auction-id"`
	// Array of advisory messages that are being requested to be produced
	EventTypes []string `json:"event-types"`
	Ids []string `json:"ids"`
	Initiator *CommonInitiator `json:"initiator,omitempty"`
}

type _AeAdvisoryRequestAssetDetail AeAdvisoryRequestAssetDetail

// NewAeAdvisoryRequestAssetDetail instantiates a new AeAdvisoryRequestAssetDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAeAdvisoryRequestAssetDetail(auctionId string, eventTypes []string, ids []string) *AeAdvisoryRequestAssetDetail {
	this := AeAdvisoryRequestAssetDetail{}
	this.AuctionId = auctionId
	this.EventTypes = eventTypes
	this.Ids = ids
	return &this
}

// NewAeAdvisoryRequestAssetDetailWithDefaults instantiates a new AeAdvisoryRequestAssetDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAeAdvisoryRequestAssetDetailWithDefaults() *AeAdvisoryRequestAssetDetail {
	this := AeAdvisoryRequestAssetDetail{}
	return &this
}

// GetAuctionId returns the AuctionId field value
func (o *AeAdvisoryRequestAssetDetail) GetAuctionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuctionId
}

// GetAuctionIdOk returns a tuple with the AuctionId field value
// and a boolean to check if the value has been set.
func (o *AeAdvisoryRequestAssetDetail) GetAuctionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuctionId, true
}

// SetAuctionId sets field value
func (o *AeAdvisoryRequestAssetDetail) SetAuctionId(v string) {
	o.AuctionId = v
}

// GetEventTypes returns the EventTypes field value
func (o *AeAdvisoryRequestAssetDetail) GetEventTypes() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.EventTypes
}

// GetEventTypesOk returns a tuple with the EventTypes field value
// and a boolean to check if the value has been set.
func (o *AeAdvisoryRequestAssetDetail) GetEventTypesOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.EventTypes, true
}

// SetEventTypes sets field value
func (o *AeAdvisoryRequestAssetDetail) SetEventTypes(v []string) {
	o.EventTypes = v
}

// GetIds returns the Ids field value
func (o *AeAdvisoryRequestAssetDetail) GetIds() []string {
	if o == nil {
		var ret []string
		return ret
	}

	return o.Ids
}

// GetIdsOk returns a tuple with the Ids field value
// and a boolean to check if the value has been set.
func (o *AeAdvisoryRequestAssetDetail) GetIdsOk() ([]string, bool) {
	if o == nil {
		return nil, false
	}
	return o.Ids, true
}

// SetIds sets field value
func (o *AeAdvisoryRequestAssetDetail) SetIds(v []string) {
	o.Ids = v
}

// GetInitiator returns the Initiator field value if set, zero value otherwise.
func (o *AeAdvisoryRequestAssetDetail) GetInitiator() CommonInitiator {
	if o == nil || IsNil(o.Initiator) {
		var ret CommonInitiator
		return ret
	}
	return *o.Initiator
}

// GetInitiatorOk returns a tuple with the Initiator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAdvisoryRequestAssetDetail) GetInitiatorOk() (*CommonInitiator, bool) {
	if o == nil || IsNil(o.Initiator) {
		return nil, false
	}
	return o.Initiator, true
}

// HasInitiator returns a boolean if a field has been set.
func (o *AeAdvisoryRequestAssetDetail) HasInitiator() bool {
	if o != nil && !IsNil(o.Initiator) {
		return true
	}

	return false
}

// SetInitiator gets a reference to the given CommonInitiator and assigns it to the Initiator field.
func (o *AeAdvisoryRequestAssetDetail) SetInitiator(v CommonInitiator) {
	o.Initiator = &v
}

func (o AeAdvisoryRequestAssetDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AeAdvisoryRequestAssetDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["auction-id"] = o.AuctionId
	toSerialize["event-types"] = o.EventTypes
	toSerialize["ids"] = o.Ids
	if !IsNil(o.Initiator) {
		toSerialize["initiator"] = o.Initiator
	}
	return toSerialize, nil
}

func (o *AeAdvisoryRequestAssetDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"auction-id",
		"event-types",
		"ids",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAeAdvisoryRequestAssetDetail := _AeAdvisoryRequestAssetDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAeAdvisoryRequestAssetDetail)

	if err != nil {
		return err
	}

	*o = AeAdvisoryRequestAssetDetail(varAeAdvisoryRequestAssetDetail)

	return err
}

type NullableAeAdvisoryRequestAssetDetail struct {
	value *AeAdvisoryRequestAssetDetail
	isSet bool
}

func (v NullableAeAdvisoryRequestAssetDetail) Get() *AeAdvisoryRequestAssetDetail {
	return v.value
}

func (v *NullableAeAdvisoryRequestAssetDetail) Set(val *AeAdvisoryRequestAssetDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableAeAdvisoryRequestAssetDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableAeAdvisoryRequestAssetDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAeAdvisoryRequestAssetDetail(val *AeAdvisoryRequestAssetDetail) *NullableAeAdvisoryRequestAssetDetail {
	return &NullableAeAdvisoryRequestAssetDetail{value: val, isSet: true}
}

func (v NullableAeAdvisoryRequestAssetDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAeAdvisoryRequestAssetDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


