/*
Edge Event Schemas

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package events

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the AeAssetDealUnsoldDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AeAssetDealUnsoldDetail{}

// AeAssetDealUnsoldDetail Vehicle unsold event.
type AeAssetDealUnsoldDetail struct {
	// Auction Edge unique identifier for an auction.
	AuctionId string `json:"auction-id"`
	Asset *CommonAmsAssetPointer `json:"asset,omitempty"`
	// Unique id for a deal
	DealId *string `json:"deal-id,omitempty"`
	// The Vehicle Identification Number(VIN) of the asset.
	Vin string `json:"vin"`
	// The stock number of the asset.
	Stock string `json:"stock"`
	// The sale date of the deal.
	SaleDate string `json:"sale-date"`
	// The lane the asset was in when deal made.
	Lane string `json:"lane"`
	// The lot the asset was in when deal made.
	Lot string `json:"lot"`
	// The updated date time of the deal.
	UpdatedAt *time.Time `json:"updated-at,omitempty"`
	Initiator *CommonInitiator `json:"initiator,omitempty"`
}

type _AeAssetDealUnsoldDetail AeAssetDealUnsoldDetail

// NewAeAssetDealUnsoldDetail instantiates a new AeAssetDealUnsoldDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAeAssetDealUnsoldDetail(auctionId string, vin string, stock string, saleDate string, lane string, lot string) *AeAssetDealUnsoldDetail {
	this := AeAssetDealUnsoldDetail{}
	this.AuctionId = auctionId
	this.Vin = vin
	this.Stock = stock
	this.SaleDate = saleDate
	this.Lane = lane
	this.Lot = lot
	return &this
}

// NewAeAssetDealUnsoldDetailWithDefaults instantiates a new AeAssetDealUnsoldDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAeAssetDealUnsoldDetailWithDefaults() *AeAssetDealUnsoldDetail {
	this := AeAssetDealUnsoldDetail{}
	return &this
}

// GetAuctionId returns the AuctionId field value
func (o *AeAssetDealUnsoldDetail) GetAuctionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuctionId
}

// GetAuctionIdOk returns a tuple with the AuctionId field value
// and a boolean to check if the value has been set.
func (o *AeAssetDealUnsoldDetail) GetAuctionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuctionId, true
}

// SetAuctionId sets field value
func (o *AeAssetDealUnsoldDetail) SetAuctionId(v string) {
	o.AuctionId = v
}

// GetAsset returns the Asset field value if set, zero value otherwise.
func (o *AeAssetDealUnsoldDetail) GetAsset() CommonAmsAssetPointer {
	if o == nil || IsNil(o.Asset) {
		var ret CommonAmsAssetPointer
		return ret
	}
	return *o.Asset
}

// GetAssetOk returns a tuple with the Asset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAssetDealUnsoldDetail) GetAssetOk() (*CommonAmsAssetPointer, bool) {
	if o == nil || IsNil(o.Asset) {
		return nil, false
	}
	return o.Asset, true
}

// HasAsset returns a boolean if a field has been set.
func (o *AeAssetDealUnsoldDetail) HasAsset() bool {
	if o != nil && !IsNil(o.Asset) {
		return true
	}

	return false
}

// SetAsset gets a reference to the given CommonAmsAssetPointer and assigns it to the Asset field.
func (o *AeAssetDealUnsoldDetail) SetAsset(v CommonAmsAssetPointer) {
	o.Asset = &v
}

// GetDealId returns the DealId field value if set, zero value otherwise.
func (o *AeAssetDealUnsoldDetail) GetDealId() string {
	if o == nil || IsNil(o.DealId) {
		var ret string
		return ret
	}
	return *o.DealId
}

// GetDealIdOk returns a tuple with the DealId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAssetDealUnsoldDetail) GetDealIdOk() (*string, bool) {
	if o == nil || IsNil(o.DealId) {
		return nil, false
	}
	return o.DealId, true
}

// HasDealId returns a boolean if a field has been set.
func (o *AeAssetDealUnsoldDetail) HasDealId() bool {
	if o != nil && !IsNil(o.DealId) {
		return true
	}

	return false
}

// SetDealId gets a reference to the given string and assigns it to the DealId field.
func (o *AeAssetDealUnsoldDetail) SetDealId(v string) {
	o.DealId = &v
}

// GetVin returns the Vin field value
func (o *AeAssetDealUnsoldDetail) GetVin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Vin
}

// GetVinOk returns a tuple with the Vin field value
// and a boolean to check if the value has been set.
func (o *AeAssetDealUnsoldDetail) GetVinOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vin, true
}

// SetVin sets field value
func (o *AeAssetDealUnsoldDetail) SetVin(v string) {
	o.Vin = v
}

// GetStock returns the Stock field value
func (o *AeAssetDealUnsoldDetail) GetStock() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Stock
}

// GetStockOk returns a tuple with the Stock field value
// and a boolean to check if the value has been set.
func (o *AeAssetDealUnsoldDetail) GetStockOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Stock, true
}

// SetStock sets field value
func (o *AeAssetDealUnsoldDetail) SetStock(v string) {
	o.Stock = v
}

// GetSaleDate returns the SaleDate field value
func (o *AeAssetDealUnsoldDetail) GetSaleDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SaleDate
}

// GetSaleDateOk returns a tuple with the SaleDate field value
// and a boolean to check if the value has been set.
func (o *AeAssetDealUnsoldDetail) GetSaleDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SaleDate, true
}

// SetSaleDate sets field value
func (o *AeAssetDealUnsoldDetail) SetSaleDate(v string) {
	o.SaleDate = v
}

// GetLane returns the Lane field value
func (o *AeAssetDealUnsoldDetail) GetLane() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Lane
}

// GetLaneOk returns a tuple with the Lane field value
// and a boolean to check if the value has been set.
func (o *AeAssetDealUnsoldDetail) GetLaneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lane, true
}

// SetLane sets field value
func (o *AeAssetDealUnsoldDetail) SetLane(v string) {
	o.Lane = v
}

// GetLot returns the Lot field value
func (o *AeAssetDealUnsoldDetail) GetLot() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Lot
}

// GetLotOk returns a tuple with the Lot field value
// and a boolean to check if the value has been set.
func (o *AeAssetDealUnsoldDetail) GetLotOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lot, true
}

// SetLot sets field value
func (o *AeAssetDealUnsoldDetail) SetLot(v string) {
	o.Lot = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *AeAssetDealUnsoldDetail) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAssetDealUnsoldDetail) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *AeAssetDealUnsoldDetail) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *AeAssetDealUnsoldDetail) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetInitiator returns the Initiator field value if set, zero value otherwise.
func (o *AeAssetDealUnsoldDetail) GetInitiator() CommonInitiator {
	if o == nil || IsNil(o.Initiator) {
		var ret CommonInitiator
		return ret
	}
	return *o.Initiator
}

// GetInitiatorOk returns a tuple with the Initiator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAssetDealUnsoldDetail) GetInitiatorOk() (*CommonInitiator, bool) {
	if o == nil || IsNil(o.Initiator) {
		return nil, false
	}
	return o.Initiator, true
}

// HasInitiator returns a boolean if a field has been set.
func (o *AeAssetDealUnsoldDetail) HasInitiator() bool {
	if o != nil && !IsNil(o.Initiator) {
		return true
	}

	return false
}

// SetInitiator gets a reference to the given CommonInitiator and assigns it to the Initiator field.
func (o *AeAssetDealUnsoldDetail) SetInitiator(v CommonInitiator) {
	o.Initiator = &v
}

func (o AeAssetDealUnsoldDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AeAssetDealUnsoldDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["auction-id"] = o.AuctionId
	if !IsNil(o.Asset) {
		toSerialize["asset"] = o.Asset
	}
	if !IsNil(o.DealId) {
		toSerialize["deal-id"] = o.DealId
	}
	toSerialize["vin"] = o.Vin
	toSerialize["stock"] = o.Stock
	toSerialize["sale-date"] = o.SaleDate
	toSerialize["lane"] = o.Lane
	toSerialize["lot"] = o.Lot
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated-at"] = o.UpdatedAt
	}
	if !IsNil(o.Initiator) {
		toSerialize["initiator"] = o.Initiator
	}
	return toSerialize, nil
}

func (o *AeAssetDealUnsoldDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"auction-id",
		"vin",
		"stock",
		"sale-date",
		"lane",
		"lot",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAeAssetDealUnsoldDetail := _AeAssetDealUnsoldDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAeAssetDealUnsoldDetail)

	if err != nil {
		return err
	}

	*o = AeAssetDealUnsoldDetail(varAeAssetDealUnsoldDetail)

	return err
}

type NullableAeAssetDealUnsoldDetail struct {
	value *AeAssetDealUnsoldDetail
	isSet bool
}

func (v NullableAeAssetDealUnsoldDetail) Get() *AeAssetDealUnsoldDetail {
	return v.value
}

func (v *NullableAeAssetDealUnsoldDetail) Set(val *AeAssetDealUnsoldDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableAeAssetDealUnsoldDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableAeAssetDealUnsoldDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAeAssetDealUnsoldDetail(val *AeAssetDealUnsoldDetail) *NullableAeAssetDealUnsoldDetail {
	return &NullableAeAssetDealUnsoldDetail{value: val, isSet: true}
}

func (v NullableAeAssetDealUnsoldDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAeAssetDealUnsoldDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


