/*
Edge Event Schemas

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package events

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AeAssetDealPaymentStatusChangedDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AeAssetDealPaymentStatusChangedDetail{}

// AeAssetDealPaymentStatusChangedDetail Event fired when status of a payment is changing.
type AeAssetDealPaymentStatusChangedDetail struct {
	// Auction Edge unique identifier for an auction.
	AuctionId string `json:"auction-id"`
	// Source's unique identifier for asset
	AssetId string `json:"asset-id"`
	// The stock number of the asset.
	Stock string `json:"stock"`
	// The Vehicle Identification Number(VIN) of the asset.
	Vin string `json:"vin"`
	Initiator *CommonInitiator `json:"initiator,omitempty"`
	Deal AeAssetDealPaymentStatusChangedDetailDeal `json:"deal"`
}

type _AeAssetDealPaymentStatusChangedDetail AeAssetDealPaymentStatusChangedDetail

// NewAeAssetDealPaymentStatusChangedDetail instantiates a new AeAssetDealPaymentStatusChangedDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAeAssetDealPaymentStatusChangedDetail(auctionId string, assetId string, stock string, vin string, deal AeAssetDealPaymentStatusChangedDetailDeal) *AeAssetDealPaymentStatusChangedDetail {
	this := AeAssetDealPaymentStatusChangedDetail{}
	this.AuctionId = auctionId
	this.AssetId = assetId
	this.Stock = stock
	this.Vin = vin
	this.Deal = deal
	return &this
}

// NewAeAssetDealPaymentStatusChangedDetailWithDefaults instantiates a new AeAssetDealPaymentStatusChangedDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAeAssetDealPaymentStatusChangedDetailWithDefaults() *AeAssetDealPaymentStatusChangedDetail {
	this := AeAssetDealPaymentStatusChangedDetail{}
	return &this
}

// GetAuctionId returns the AuctionId field value
func (o *AeAssetDealPaymentStatusChangedDetail) GetAuctionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuctionId
}

// GetAuctionIdOk returns a tuple with the AuctionId field value
// and a boolean to check if the value has been set.
func (o *AeAssetDealPaymentStatusChangedDetail) GetAuctionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuctionId, true
}

// SetAuctionId sets field value
func (o *AeAssetDealPaymentStatusChangedDetail) SetAuctionId(v string) {
	o.AuctionId = v
}

// GetAssetId returns the AssetId field value
func (o *AeAssetDealPaymentStatusChangedDetail) GetAssetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value
// and a boolean to check if the value has been set.
func (o *AeAssetDealPaymentStatusChangedDetail) GetAssetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetId, true
}

// SetAssetId sets field value
func (o *AeAssetDealPaymentStatusChangedDetail) SetAssetId(v string) {
	o.AssetId = v
}

// GetStock returns the Stock field value
func (o *AeAssetDealPaymentStatusChangedDetail) GetStock() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Stock
}

// GetStockOk returns a tuple with the Stock field value
// and a boolean to check if the value has been set.
func (o *AeAssetDealPaymentStatusChangedDetail) GetStockOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Stock, true
}

// SetStock sets field value
func (o *AeAssetDealPaymentStatusChangedDetail) SetStock(v string) {
	o.Stock = v
}

// GetVin returns the Vin field value
func (o *AeAssetDealPaymentStatusChangedDetail) GetVin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Vin
}

// GetVinOk returns a tuple with the Vin field value
// and a boolean to check if the value has been set.
func (o *AeAssetDealPaymentStatusChangedDetail) GetVinOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vin, true
}

// SetVin sets field value
func (o *AeAssetDealPaymentStatusChangedDetail) SetVin(v string) {
	o.Vin = v
}

// GetInitiator returns the Initiator field value if set, zero value otherwise.
func (o *AeAssetDealPaymentStatusChangedDetail) GetInitiator() CommonInitiator {
	if o == nil || IsNil(o.Initiator) {
		var ret CommonInitiator
		return ret
	}
	return *o.Initiator
}

// GetInitiatorOk returns a tuple with the Initiator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAssetDealPaymentStatusChangedDetail) GetInitiatorOk() (*CommonInitiator, bool) {
	if o == nil || IsNil(o.Initiator) {
		return nil, false
	}
	return o.Initiator, true
}

// HasInitiator returns a boolean if a field has been set.
func (o *AeAssetDealPaymentStatusChangedDetail) HasInitiator() bool {
	if o != nil && !IsNil(o.Initiator) {
		return true
	}

	return false
}

// SetInitiator gets a reference to the given CommonInitiator and assigns it to the Initiator field.
func (o *AeAssetDealPaymentStatusChangedDetail) SetInitiator(v CommonInitiator) {
	o.Initiator = &v
}

// GetDeal returns the Deal field value
func (o *AeAssetDealPaymentStatusChangedDetail) GetDeal() AeAssetDealPaymentStatusChangedDetailDeal {
	if o == nil {
		var ret AeAssetDealPaymentStatusChangedDetailDeal
		return ret
	}

	return o.Deal
}

// GetDealOk returns a tuple with the Deal field value
// and a boolean to check if the value has been set.
func (o *AeAssetDealPaymentStatusChangedDetail) GetDealOk() (*AeAssetDealPaymentStatusChangedDetailDeal, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Deal, true
}

// SetDeal sets field value
func (o *AeAssetDealPaymentStatusChangedDetail) SetDeal(v AeAssetDealPaymentStatusChangedDetailDeal) {
	o.Deal = v
}

func (o AeAssetDealPaymentStatusChangedDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AeAssetDealPaymentStatusChangedDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["auction-id"] = o.AuctionId
	toSerialize["asset-id"] = o.AssetId
	toSerialize["stock"] = o.Stock
	toSerialize["vin"] = o.Vin
	if !IsNil(o.Initiator) {
		toSerialize["initiator"] = o.Initiator
	}
	toSerialize["deal"] = o.Deal
	return toSerialize, nil
}

func (o *AeAssetDealPaymentStatusChangedDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"auction-id",
		"asset-id",
		"stock",
		"vin",
		"deal",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAeAssetDealPaymentStatusChangedDetail := _AeAssetDealPaymentStatusChangedDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAeAssetDealPaymentStatusChangedDetail)

	if err != nil {
		return err
	}

	*o = AeAssetDealPaymentStatusChangedDetail(varAeAssetDealPaymentStatusChangedDetail)

	return err
}

type NullableAeAssetDealPaymentStatusChangedDetail struct {
	value *AeAssetDealPaymentStatusChangedDetail
	isSet bool
}

func (v NullableAeAssetDealPaymentStatusChangedDetail) Get() *AeAssetDealPaymentStatusChangedDetail {
	return v.value
}

func (v *NullableAeAssetDealPaymentStatusChangedDetail) Set(val *AeAssetDealPaymentStatusChangedDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableAeAssetDealPaymentStatusChangedDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableAeAssetDealPaymentStatusChangedDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAeAssetDealPaymentStatusChangedDetail(val *AeAssetDealPaymentStatusChangedDetail) *NullableAeAssetDealPaymentStatusChangedDetail {
	return &NullableAeAssetDealPaymentStatusChangedDetail{value: val, isSet: true}
}

func (v NullableAeAssetDealPaymentStatusChangedDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAeAssetDealPaymentStatusChangedDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


