/*
Edge Event Schemas

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package events

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the AeAdvisoryAccountRepresentativesAmsDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AeAdvisoryAccountRepresentativesAmsDetail{}

// AeAdvisoryAccountRepresentativesAmsDetail Advisory Account Representatives event for AMS accounts
type AeAdvisoryAccountRepresentativesAmsDetail struct {
	// Auction Edge unique identifier for an auction.
	AuctionId string `json:"auction-id"`
	Account CommonAmsAccountPointer `json:"account"`
	// The time in ISO-8601 formatted at which the record was generated
	UpdatedAt time.Time `json:"updated-at"`
	// The representatives and their permissions for the account
	Representatives []AeAdvisoryAccountRepresentativesAmsDetailRepresentativesInner `json:"representatives"`
	Initiator *CommonInitiator `json:"initiator,omitempty"`
}

type _AeAdvisoryAccountRepresentativesAmsDetail AeAdvisoryAccountRepresentativesAmsDetail

// NewAeAdvisoryAccountRepresentativesAmsDetail instantiates a new AeAdvisoryAccountRepresentativesAmsDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAeAdvisoryAccountRepresentativesAmsDetail(auctionId string, account CommonAmsAccountPointer, updatedAt time.Time, representatives []AeAdvisoryAccountRepresentativesAmsDetailRepresentativesInner) *AeAdvisoryAccountRepresentativesAmsDetail {
	this := AeAdvisoryAccountRepresentativesAmsDetail{}
	this.AuctionId = auctionId
	this.Account = account
	this.UpdatedAt = updatedAt
	this.Representatives = representatives
	return &this
}

// NewAeAdvisoryAccountRepresentativesAmsDetailWithDefaults instantiates a new AeAdvisoryAccountRepresentativesAmsDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAeAdvisoryAccountRepresentativesAmsDetailWithDefaults() *AeAdvisoryAccountRepresentativesAmsDetail {
	this := AeAdvisoryAccountRepresentativesAmsDetail{}
	return &this
}

// GetAuctionId returns the AuctionId field value
func (o *AeAdvisoryAccountRepresentativesAmsDetail) GetAuctionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuctionId
}

// GetAuctionIdOk returns a tuple with the AuctionId field value
// and a boolean to check if the value has been set.
func (o *AeAdvisoryAccountRepresentativesAmsDetail) GetAuctionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuctionId, true
}

// SetAuctionId sets field value
func (o *AeAdvisoryAccountRepresentativesAmsDetail) SetAuctionId(v string) {
	o.AuctionId = v
}

// GetAccount returns the Account field value
func (o *AeAdvisoryAccountRepresentativesAmsDetail) GetAccount() CommonAmsAccountPointer {
	if o == nil {
		var ret CommonAmsAccountPointer
		return ret
	}

	return o.Account
}

// GetAccountOk returns a tuple with the Account field value
// and a boolean to check if the value has been set.
func (o *AeAdvisoryAccountRepresentativesAmsDetail) GetAccountOk() (*CommonAmsAccountPointer, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Account, true
}

// SetAccount sets field value
func (o *AeAdvisoryAccountRepresentativesAmsDetail) SetAccount(v CommonAmsAccountPointer) {
	o.Account = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *AeAdvisoryAccountRepresentativesAmsDetail) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *AeAdvisoryAccountRepresentativesAmsDetail) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *AeAdvisoryAccountRepresentativesAmsDetail) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetRepresentatives returns the Representatives field value
func (o *AeAdvisoryAccountRepresentativesAmsDetail) GetRepresentatives() []AeAdvisoryAccountRepresentativesAmsDetailRepresentativesInner {
	if o == nil {
		var ret []AeAdvisoryAccountRepresentativesAmsDetailRepresentativesInner
		return ret
	}

	return o.Representatives
}

// GetRepresentativesOk returns a tuple with the Representatives field value
// and a boolean to check if the value has been set.
func (o *AeAdvisoryAccountRepresentativesAmsDetail) GetRepresentativesOk() ([]AeAdvisoryAccountRepresentativesAmsDetailRepresentativesInner, bool) {
	if o == nil {
		return nil, false
	}
	return o.Representatives, true
}

// SetRepresentatives sets field value
func (o *AeAdvisoryAccountRepresentativesAmsDetail) SetRepresentatives(v []AeAdvisoryAccountRepresentativesAmsDetailRepresentativesInner) {
	o.Representatives = v
}

// GetInitiator returns the Initiator field value if set, zero value otherwise.
func (o *AeAdvisoryAccountRepresentativesAmsDetail) GetInitiator() CommonInitiator {
	if o == nil || IsNil(o.Initiator) {
		var ret CommonInitiator
		return ret
	}
	return *o.Initiator
}

// GetInitiatorOk returns a tuple with the Initiator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAdvisoryAccountRepresentativesAmsDetail) GetInitiatorOk() (*CommonInitiator, bool) {
	if o == nil || IsNil(o.Initiator) {
		return nil, false
	}
	return o.Initiator, true
}

// HasInitiator returns a boolean if a field has been set.
func (o *AeAdvisoryAccountRepresentativesAmsDetail) HasInitiator() bool {
	if o != nil && !IsNil(o.Initiator) {
		return true
	}

	return false
}

// SetInitiator gets a reference to the given CommonInitiator and assigns it to the Initiator field.
func (o *AeAdvisoryAccountRepresentativesAmsDetail) SetInitiator(v CommonInitiator) {
	o.Initiator = &v
}

func (o AeAdvisoryAccountRepresentativesAmsDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AeAdvisoryAccountRepresentativesAmsDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["auction-id"] = o.AuctionId
	toSerialize["account"] = o.Account
	toSerialize["updated-at"] = o.UpdatedAt
	toSerialize["representatives"] = o.Representatives
	if !IsNil(o.Initiator) {
		toSerialize["initiator"] = o.Initiator
	}
	return toSerialize, nil
}

func (o *AeAdvisoryAccountRepresentativesAmsDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"auction-id",
		"account",
		"updated-at",
		"representatives",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAeAdvisoryAccountRepresentativesAmsDetail := _AeAdvisoryAccountRepresentativesAmsDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAeAdvisoryAccountRepresentativesAmsDetail)

	if err != nil {
		return err
	}

	*o = AeAdvisoryAccountRepresentativesAmsDetail(varAeAdvisoryAccountRepresentativesAmsDetail)

	return err
}

type NullableAeAdvisoryAccountRepresentativesAmsDetail struct {
	value *AeAdvisoryAccountRepresentativesAmsDetail
	isSet bool
}

func (v NullableAeAdvisoryAccountRepresentativesAmsDetail) Get() *AeAdvisoryAccountRepresentativesAmsDetail {
	return v.value
}

func (v *NullableAeAdvisoryAccountRepresentativesAmsDetail) Set(val *AeAdvisoryAccountRepresentativesAmsDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableAeAdvisoryAccountRepresentativesAmsDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableAeAdvisoryAccountRepresentativesAmsDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAeAdvisoryAccountRepresentativesAmsDetail(val *AeAdvisoryAccountRepresentativesAmsDetail) *NullableAeAdvisoryAccountRepresentativesAmsDetail {
	return &NullableAeAdvisoryAccountRepresentativesAmsDetail{value: val, isSet: true}
}

func (v NullableAeAdvisoryAccountRepresentativesAmsDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAeAdvisoryAccountRepresentativesAmsDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


