/*
Edge Event Schemas

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package events

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AeAssetDealPaymentApplySourceDetailDeal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AeAssetDealPaymentApplySourceDetailDeal{}

// AeAssetDealPaymentApplySourceDetailDeal struct for AeAssetDealPaymentApplySourceDetailDeal
type AeAssetDealPaymentApplySourceDetailDeal struct {
	// Unique id for a deal
	Id *string `json:"id,omitempty"`
	Buyer CommonAmsAccountPointer `json:"buyer"`
	Payment AeAssetDealPaymentApplySourceDetailDealPayment `json:"payment"`
}

type _AeAssetDealPaymentApplySourceDetailDeal AeAssetDealPaymentApplySourceDetailDeal

// NewAeAssetDealPaymentApplySourceDetailDeal instantiates a new AeAssetDealPaymentApplySourceDetailDeal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAeAssetDealPaymentApplySourceDetailDeal(buyer CommonAmsAccountPointer, payment AeAssetDealPaymentApplySourceDetailDealPayment) *AeAssetDealPaymentApplySourceDetailDeal {
	this := AeAssetDealPaymentApplySourceDetailDeal{}
	this.Buyer = buyer
	this.Payment = payment
	return &this
}

// NewAeAssetDealPaymentApplySourceDetailDealWithDefaults instantiates a new AeAssetDealPaymentApplySourceDetailDeal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAeAssetDealPaymentApplySourceDetailDealWithDefaults() *AeAssetDealPaymentApplySourceDetailDeal {
	this := AeAssetDealPaymentApplySourceDetailDeal{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AeAssetDealPaymentApplySourceDetailDeal) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAssetDealPaymentApplySourceDetailDeal) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AeAssetDealPaymentApplySourceDetailDeal) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AeAssetDealPaymentApplySourceDetailDeal) SetId(v string) {
	o.Id = &v
}

// GetBuyer returns the Buyer field value
func (o *AeAssetDealPaymentApplySourceDetailDeal) GetBuyer() CommonAmsAccountPointer {
	if o == nil {
		var ret CommonAmsAccountPointer
		return ret
	}

	return o.Buyer
}

// GetBuyerOk returns a tuple with the Buyer field value
// and a boolean to check if the value has been set.
func (o *AeAssetDealPaymentApplySourceDetailDeal) GetBuyerOk() (*CommonAmsAccountPointer, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Buyer, true
}

// SetBuyer sets field value
func (o *AeAssetDealPaymentApplySourceDetailDeal) SetBuyer(v CommonAmsAccountPointer) {
	o.Buyer = v
}

// GetPayment returns the Payment field value
func (o *AeAssetDealPaymentApplySourceDetailDeal) GetPayment() AeAssetDealPaymentApplySourceDetailDealPayment {
	if o == nil {
		var ret AeAssetDealPaymentApplySourceDetailDealPayment
		return ret
	}

	return o.Payment
}

// GetPaymentOk returns a tuple with the Payment field value
// and a boolean to check if the value has been set.
func (o *AeAssetDealPaymentApplySourceDetailDeal) GetPaymentOk() (*AeAssetDealPaymentApplySourceDetailDealPayment, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Payment, true
}

// SetPayment sets field value
func (o *AeAssetDealPaymentApplySourceDetailDeal) SetPayment(v AeAssetDealPaymentApplySourceDetailDealPayment) {
	o.Payment = v
}

func (o AeAssetDealPaymentApplySourceDetailDeal) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AeAssetDealPaymentApplySourceDetailDeal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	toSerialize["buyer"] = o.Buyer
	toSerialize["payment"] = o.Payment
	return toSerialize, nil
}

func (o *AeAssetDealPaymentApplySourceDetailDeal) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"buyer",
		"payment",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAeAssetDealPaymentApplySourceDetailDeal := _AeAssetDealPaymentApplySourceDetailDeal{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAeAssetDealPaymentApplySourceDetailDeal)

	if err != nil {
		return err
	}

	*o = AeAssetDealPaymentApplySourceDetailDeal(varAeAssetDealPaymentApplySourceDetailDeal)

	return err
}

type NullableAeAssetDealPaymentApplySourceDetailDeal struct {
	value *AeAssetDealPaymentApplySourceDetailDeal
	isSet bool
}

func (v NullableAeAssetDealPaymentApplySourceDetailDeal) Get() *AeAssetDealPaymentApplySourceDetailDeal {
	return v.value
}

func (v *NullableAeAssetDealPaymentApplySourceDetailDeal) Set(val *AeAssetDealPaymentApplySourceDetailDeal) {
	v.value = val
	v.isSet = true
}

func (v NullableAeAssetDealPaymentApplySourceDetailDeal) IsSet() bool {
	return v.isSet
}

func (v *NullableAeAssetDealPaymentApplySourceDetailDeal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAeAssetDealPaymentApplySourceDetailDeal(val *AeAssetDealPaymentApplySourceDetailDeal) *NullableAeAssetDealPaymentApplySourceDetailDeal {
	return &NullableAeAssetDealPaymentApplySourceDetailDeal{value: val, isSet: true}
}

func (v NullableAeAssetDealPaymentApplySourceDetailDeal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAeAssetDealPaymentApplySourceDetailDeal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


