/*
Edge Event Schemas

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package events

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AeAssetSellerChargeRemovedDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AeAssetSellerChargeRemovedDetail{}

// AeAssetSellerChargeRemovedDetail triggered when a seller charge is removed successfully.
type AeAssetSellerChargeRemovedDetail struct {
	// Auction Edge unique identifier for an auction.
	AuctionId string `json:"auction-id"`
	// Unique identifier of the charge being removed.
	ChargeId string `json:"charge-id"`
	Seller CommonAmsAccountPointer `json:"seller"`
	Asset CommonAmsAssetPointer `json:"asset"`
	// Unique identifier referencing the remove request event that removed the charge
	RemoveRequestReferenceId NullableString `json:"remove-request-reference-id,omitempty"`
	Initiator *CommonInitiator `json:"initiator,omitempty"`
}

type _AeAssetSellerChargeRemovedDetail AeAssetSellerChargeRemovedDetail

// NewAeAssetSellerChargeRemovedDetail instantiates a new AeAssetSellerChargeRemovedDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAeAssetSellerChargeRemovedDetail(auctionId string, chargeId string, seller CommonAmsAccountPointer, asset CommonAmsAssetPointer) *AeAssetSellerChargeRemovedDetail {
	this := AeAssetSellerChargeRemovedDetail{}
	this.AuctionId = auctionId
	this.ChargeId = chargeId
	this.Seller = seller
	this.Asset = asset
	return &this
}

// NewAeAssetSellerChargeRemovedDetailWithDefaults instantiates a new AeAssetSellerChargeRemovedDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAeAssetSellerChargeRemovedDetailWithDefaults() *AeAssetSellerChargeRemovedDetail {
	this := AeAssetSellerChargeRemovedDetail{}
	return &this
}

// GetAuctionId returns the AuctionId field value
func (o *AeAssetSellerChargeRemovedDetail) GetAuctionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuctionId
}

// GetAuctionIdOk returns a tuple with the AuctionId field value
// and a boolean to check if the value has been set.
func (o *AeAssetSellerChargeRemovedDetail) GetAuctionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuctionId, true
}

// SetAuctionId sets field value
func (o *AeAssetSellerChargeRemovedDetail) SetAuctionId(v string) {
	o.AuctionId = v
}

// GetChargeId returns the ChargeId field value
func (o *AeAssetSellerChargeRemovedDetail) GetChargeId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.ChargeId
}

// GetChargeIdOk returns a tuple with the ChargeId field value
// and a boolean to check if the value has been set.
func (o *AeAssetSellerChargeRemovedDetail) GetChargeIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.ChargeId, true
}

// SetChargeId sets field value
func (o *AeAssetSellerChargeRemovedDetail) SetChargeId(v string) {
	o.ChargeId = v
}

// GetSeller returns the Seller field value
func (o *AeAssetSellerChargeRemovedDetail) GetSeller() CommonAmsAccountPointer {
	if o == nil {
		var ret CommonAmsAccountPointer
		return ret
	}

	return o.Seller
}

// GetSellerOk returns a tuple with the Seller field value
// and a boolean to check if the value has been set.
func (o *AeAssetSellerChargeRemovedDetail) GetSellerOk() (*CommonAmsAccountPointer, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Seller, true
}

// SetSeller sets field value
func (o *AeAssetSellerChargeRemovedDetail) SetSeller(v CommonAmsAccountPointer) {
	o.Seller = v
}

// GetAsset returns the Asset field value
func (o *AeAssetSellerChargeRemovedDetail) GetAsset() CommonAmsAssetPointer {
	if o == nil {
		var ret CommonAmsAssetPointer
		return ret
	}

	return o.Asset
}

// GetAssetOk returns a tuple with the Asset field value
// and a boolean to check if the value has been set.
func (o *AeAssetSellerChargeRemovedDetail) GetAssetOk() (*CommonAmsAssetPointer, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asset, true
}

// SetAsset sets field value
func (o *AeAssetSellerChargeRemovedDetail) SetAsset(v CommonAmsAssetPointer) {
	o.Asset = v
}

// GetRemoveRequestReferenceId returns the RemoveRequestReferenceId field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AeAssetSellerChargeRemovedDetail) GetRemoveRequestReferenceId() string {
	if o == nil || IsNil(o.RemoveRequestReferenceId.Get()) {
		var ret string
		return ret
	}
	return *o.RemoveRequestReferenceId.Get()
}

// GetRemoveRequestReferenceIdOk returns a tuple with the RemoveRequestReferenceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AeAssetSellerChargeRemovedDetail) GetRemoveRequestReferenceIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.RemoveRequestReferenceId.Get(), o.RemoveRequestReferenceId.IsSet()
}

// HasRemoveRequestReferenceId returns a boolean if a field has been set.
func (o *AeAssetSellerChargeRemovedDetail) HasRemoveRequestReferenceId() bool {
	if o != nil && o.RemoveRequestReferenceId.IsSet() {
		return true
	}

	return false
}

// SetRemoveRequestReferenceId gets a reference to the given NullableString and assigns it to the RemoveRequestReferenceId field.
func (o *AeAssetSellerChargeRemovedDetail) SetRemoveRequestReferenceId(v string) {
	o.RemoveRequestReferenceId.Set(&v)
}
// SetRemoveRequestReferenceIdNil sets the value for RemoveRequestReferenceId to be an explicit nil
func (o *AeAssetSellerChargeRemovedDetail) SetRemoveRequestReferenceIdNil() {
	o.RemoveRequestReferenceId.Set(nil)
}

// UnsetRemoveRequestReferenceId ensures that no value is present for RemoveRequestReferenceId, not even an explicit nil
func (o *AeAssetSellerChargeRemovedDetail) UnsetRemoveRequestReferenceId() {
	o.RemoveRequestReferenceId.Unset()
}

// GetInitiator returns the Initiator field value if set, zero value otherwise.
func (o *AeAssetSellerChargeRemovedDetail) GetInitiator() CommonInitiator {
	if o == nil || IsNil(o.Initiator) {
		var ret CommonInitiator
		return ret
	}
	return *o.Initiator
}

// GetInitiatorOk returns a tuple with the Initiator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAssetSellerChargeRemovedDetail) GetInitiatorOk() (*CommonInitiator, bool) {
	if o == nil || IsNil(o.Initiator) {
		return nil, false
	}
	return o.Initiator, true
}

// HasInitiator returns a boolean if a field has been set.
func (o *AeAssetSellerChargeRemovedDetail) HasInitiator() bool {
	if o != nil && !IsNil(o.Initiator) {
		return true
	}

	return false
}

// SetInitiator gets a reference to the given CommonInitiator and assigns it to the Initiator field.
func (o *AeAssetSellerChargeRemovedDetail) SetInitiator(v CommonInitiator) {
	o.Initiator = &v
}

func (o AeAssetSellerChargeRemovedDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AeAssetSellerChargeRemovedDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["auction-id"] = o.AuctionId
	toSerialize["charge-id"] = o.ChargeId
	toSerialize["seller"] = o.Seller
	toSerialize["asset"] = o.Asset
	if o.RemoveRequestReferenceId.IsSet() {
		toSerialize["remove-request-reference-id"] = o.RemoveRequestReferenceId.Get()
	}
	if !IsNil(o.Initiator) {
		toSerialize["initiator"] = o.Initiator
	}
	return toSerialize, nil
}

func (o *AeAssetSellerChargeRemovedDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"auction-id",
		"charge-id",
		"seller",
		"asset",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAeAssetSellerChargeRemovedDetail := _AeAssetSellerChargeRemovedDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAeAssetSellerChargeRemovedDetail)

	if err != nil {
		return err
	}

	*o = AeAssetSellerChargeRemovedDetail(varAeAssetSellerChargeRemovedDetail)

	return err
}

type NullableAeAssetSellerChargeRemovedDetail struct {
	value *AeAssetSellerChargeRemovedDetail
	isSet bool
}

func (v NullableAeAssetSellerChargeRemovedDetail) Get() *AeAssetSellerChargeRemovedDetail {
	return v.value
}

func (v *NullableAeAssetSellerChargeRemovedDetail) Set(val *AeAssetSellerChargeRemovedDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableAeAssetSellerChargeRemovedDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableAeAssetSellerChargeRemovedDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAeAssetSellerChargeRemovedDetail(val *AeAssetSellerChargeRemovedDetail) *NullableAeAssetSellerChargeRemovedDetail {
	return &NullableAeAssetSellerChargeRemovedDetail{value: val, isSet: true}
}

func (v NullableAeAssetSellerChargeRemovedDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAeAssetSellerChargeRemovedDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


