/*
Edge Event Schemas

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package events

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AeAssetGatepassCreatedDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AeAssetGatepassCreatedDetail{}

// AeAssetGatepassCreatedDetail Notification that a gatepass document has been created
type AeAssetGatepassCreatedDetail struct {
	// Auction Edge unique identifier for an auction.
	AuctionId string `json:"auction-id"`
	Asset *CommonAmsAssetPointer `json:"asset,omitempty"`
	// The Vehicle Identification Number(VIN) of the asset.
	Vin string `json:"vin"`
	// The stock number of the asset.
	Stock string `json:"stock"`
	// URI to download the document
	DownloadUri string `json:"download-uri"`
	Initiator *CommonInitiator `json:"initiator,omitempty"`
}

type _AeAssetGatepassCreatedDetail AeAssetGatepassCreatedDetail

// NewAeAssetGatepassCreatedDetail instantiates a new AeAssetGatepassCreatedDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAeAssetGatepassCreatedDetail(auctionId string, vin string, stock string, downloadUri string) *AeAssetGatepassCreatedDetail {
	this := AeAssetGatepassCreatedDetail{}
	this.AuctionId = auctionId
	this.Vin = vin
	this.Stock = stock
	this.DownloadUri = downloadUri
	return &this
}

// NewAeAssetGatepassCreatedDetailWithDefaults instantiates a new AeAssetGatepassCreatedDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAeAssetGatepassCreatedDetailWithDefaults() *AeAssetGatepassCreatedDetail {
	this := AeAssetGatepassCreatedDetail{}
	return &this
}

// GetAuctionId returns the AuctionId field value
func (o *AeAssetGatepassCreatedDetail) GetAuctionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuctionId
}

// GetAuctionIdOk returns a tuple with the AuctionId field value
// and a boolean to check if the value has been set.
func (o *AeAssetGatepassCreatedDetail) GetAuctionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuctionId, true
}

// SetAuctionId sets field value
func (o *AeAssetGatepassCreatedDetail) SetAuctionId(v string) {
	o.AuctionId = v
}

// GetAsset returns the Asset field value if set, zero value otherwise.
func (o *AeAssetGatepassCreatedDetail) GetAsset() CommonAmsAssetPointer {
	if o == nil || IsNil(o.Asset) {
		var ret CommonAmsAssetPointer
		return ret
	}
	return *o.Asset
}

// GetAssetOk returns a tuple with the Asset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAssetGatepassCreatedDetail) GetAssetOk() (*CommonAmsAssetPointer, bool) {
	if o == nil || IsNil(o.Asset) {
		return nil, false
	}
	return o.Asset, true
}

// HasAsset returns a boolean if a field has been set.
func (o *AeAssetGatepassCreatedDetail) HasAsset() bool {
	if o != nil && !IsNil(o.Asset) {
		return true
	}

	return false
}

// SetAsset gets a reference to the given CommonAmsAssetPointer and assigns it to the Asset field.
func (o *AeAssetGatepassCreatedDetail) SetAsset(v CommonAmsAssetPointer) {
	o.Asset = &v
}

// GetVin returns the Vin field value
func (o *AeAssetGatepassCreatedDetail) GetVin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Vin
}

// GetVinOk returns a tuple with the Vin field value
// and a boolean to check if the value has been set.
func (o *AeAssetGatepassCreatedDetail) GetVinOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vin, true
}

// SetVin sets field value
func (o *AeAssetGatepassCreatedDetail) SetVin(v string) {
	o.Vin = v
}

// GetStock returns the Stock field value
func (o *AeAssetGatepassCreatedDetail) GetStock() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Stock
}

// GetStockOk returns a tuple with the Stock field value
// and a boolean to check if the value has been set.
func (o *AeAssetGatepassCreatedDetail) GetStockOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Stock, true
}

// SetStock sets field value
func (o *AeAssetGatepassCreatedDetail) SetStock(v string) {
	o.Stock = v
}

// GetDownloadUri returns the DownloadUri field value
func (o *AeAssetGatepassCreatedDetail) GetDownloadUri() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.DownloadUri
}

// GetDownloadUriOk returns a tuple with the DownloadUri field value
// and a boolean to check if the value has been set.
func (o *AeAssetGatepassCreatedDetail) GetDownloadUriOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.DownloadUri, true
}

// SetDownloadUri sets field value
func (o *AeAssetGatepassCreatedDetail) SetDownloadUri(v string) {
	o.DownloadUri = v
}

// GetInitiator returns the Initiator field value if set, zero value otherwise.
func (o *AeAssetGatepassCreatedDetail) GetInitiator() CommonInitiator {
	if o == nil || IsNil(o.Initiator) {
		var ret CommonInitiator
		return ret
	}
	return *o.Initiator
}

// GetInitiatorOk returns a tuple with the Initiator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAssetGatepassCreatedDetail) GetInitiatorOk() (*CommonInitiator, bool) {
	if o == nil || IsNil(o.Initiator) {
		return nil, false
	}
	return o.Initiator, true
}

// HasInitiator returns a boolean if a field has been set.
func (o *AeAssetGatepassCreatedDetail) HasInitiator() bool {
	if o != nil && !IsNil(o.Initiator) {
		return true
	}

	return false
}

// SetInitiator gets a reference to the given CommonInitiator and assigns it to the Initiator field.
func (o *AeAssetGatepassCreatedDetail) SetInitiator(v CommonInitiator) {
	o.Initiator = &v
}

func (o AeAssetGatepassCreatedDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AeAssetGatepassCreatedDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["auction-id"] = o.AuctionId
	if !IsNil(o.Asset) {
		toSerialize["asset"] = o.Asset
	}
	toSerialize["vin"] = o.Vin
	toSerialize["stock"] = o.Stock
	toSerialize["download-uri"] = o.DownloadUri
	if !IsNil(o.Initiator) {
		toSerialize["initiator"] = o.Initiator
	}
	return toSerialize, nil
}

func (o *AeAssetGatepassCreatedDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"auction-id",
		"vin",
		"stock",
		"download-uri",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAeAssetGatepassCreatedDetail := _AeAssetGatepassCreatedDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAeAssetGatepassCreatedDetail)

	if err != nil {
		return err
	}

	*o = AeAssetGatepassCreatedDetail(varAeAssetGatepassCreatedDetail)

	return err
}

type NullableAeAssetGatepassCreatedDetail struct {
	value *AeAssetGatepassCreatedDetail
	isSet bool
}

func (v NullableAeAssetGatepassCreatedDetail) Get() *AeAssetGatepassCreatedDetail {
	return v.value
}

func (v *NullableAeAssetGatepassCreatedDetail) Set(val *AeAssetGatepassCreatedDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableAeAssetGatepassCreatedDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableAeAssetGatepassCreatedDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAeAssetGatepassCreatedDetail(val *AeAssetGatepassCreatedDetail) *NullableAeAssetGatepassCreatedDetail {
	return &NullableAeAssetGatepassCreatedDetail{value: val, isSet: true}
}

func (v NullableAeAssetGatepassCreatedDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAeAssetGatepassCreatedDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


