/*
Edge Event Schemas

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package events

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AeUserInfoAdvisoryDataSourceUpdatedDetailBucket type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AeUserInfoAdvisoryDataSourceUpdatedDetailBucket{}

// AeUserInfoAdvisoryDataSourceUpdatedDetailBucket struct for AeUserInfoAdvisoryDataSourceUpdatedDetailBucket
type AeUserInfoAdvisoryDataSourceUpdatedDetailBucket struct {
	Name string `json:"name"`
}

type _AeUserInfoAdvisoryDataSourceUpdatedDetailBucket AeUserInfoAdvisoryDataSourceUpdatedDetailBucket

// NewAeUserInfoAdvisoryDataSourceUpdatedDetailBucket instantiates a new AeUserInfoAdvisoryDataSourceUpdatedDetailBucket object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAeUserInfoAdvisoryDataSourceUpdatedDetailBucket(name string) *AeUserInfoAdvisoryDataSourceUpdatedDetailBucket {
	this := AeUserInfoAdvisoryDataSourceUpdatedDetailBucket{}
	this.Name = name
	return &this
}

// NewAeUserInfoAdvisoryDataSourceUpdatedDetailBucketWithDefaults instantiates a new AeUserInfoAdvisoryDataSourceUpdatedDetailBucket object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAeUserInfoAdvisoryDataSourceUpdatedDetailBucketWithDefaults() *AeUserInfoAdvisoryDataSourceUpdatedDetailBucket {
	this := AeUserInfoAdvisoryDataSourceUpdatedDetailBucket{}
	return &this
}

// GetName returns the Name field value
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetailBucket) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetailBucket) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetailBucket) SetName(v string) {
	o.Name = v
}

func (o AeUserInfoAdvisoryDataSourceUpdatedDetailBucket) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AeUserInfoAdvisoryDataSourceUpdatedDetailBucket) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["name"] = o.Name
	return toSerialize, nil
}

func (o *AeUserInfoAdvisoryDataSourceUpdatedDetailBucket) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"name",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAeUserInfoAdvisoryDataSourceUpdatedDetailBucket := _AeUserInfoAdvisoryDataSourceUpdatedDetailBucket{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAeUserInfoAdvisoryDataSourceUpdatedDetailBucket)

	if err != nil {
		return err
	}

	*o = AeUserInfoAdvisoryDataSourceUpdatedDetailBucket(varAeUserInfoAdvisoryDataSourceUpdatedDetailBucket)

	return err
}

type NullableAeUserInfoAdvisoryDataSourceUpdatedDetailBucket struct {
	value *AeUserInfoAdvisoryDataSourceUpdatedDetailBucket
	isSet bool
}

func (v NullableAeUserInfoAdvisoryDataSourceUpdatedDetailBucket) Get() *AeUserInfoAdvisoryDataSourceUpdatedDetailBucket {
	return v.value
}

func (v *NullableAeUserInfoAdvisoryDataSourceUpdatedDetailBucket) Set(val *AeUserInfoAdvisoryDataSourceUpdatedDetailBucket) {
	v.value = val
	v.isSet = true
}

func (v NullableAeUserInfoAdvisoryDataSourceUpdatedDetailBucket) IsSet() bool {
	return v.isSet
}

func (v *NullableAeUserInfoAdvisoryDataSourceUpdatedDetailBucket) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAeUserInfoAdvisoryDataSourceUpdatedDetailBucket(val *AeUserInfoAdvisoryDataSourceUpdatedDetailBucket) *NullableAeUserInfoAdvisoryDataSourceUpdatedDetailBucket {
	return &NullableAeUserInfoAdvisoryDataSourceUpdatedDetailBucket{value: val, isSet: true}
}

func (v NullableAeUserInfoAdvisoryDataSourceUpdatedDetailBucket) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAeUserInfoAdvisoryDataSourceUpdatedDetailBucket) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


