/*
Edge Event Schemas

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package events

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AeAssetNegotiationOfferCounteredDetailOffer type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AeAssetNegotiationOfferCounteredDetailOffer{}

// AeAssetNegotiationOfferCounteredDetailOffer struct for AeAssetNegotiationOfferCounteredDetailOffer
type AeAssetNegotiationOfferCounteredDetailOffer struct {
	// unique identifier of the offer
	Id string `json:"id"`
	// the source system that created the offer
	Source string `json:"source"`
	// user that entered the offer
	AuthorizedBy string `json:"authorized-by"`
	// Deprecated
	Rep CommonAmsRepPointer `json:"rep"`
	Amount CommonCurrency `json:"amount"`
	// a noted added at the time of the offfer
	Note string `json:"note"`
	Notification CommonAssetNegotiationBaseOfferNotification `json:"notification"`
	CounteredBy CommonAssetNegotiationOfferBy `json:"countered-by"`
}

type _AeAssetNegotiationOfferCounteredDetailOffer AeAssetNegotiationOfferCounteredDetailOffer

// NewAeAssetNegotiationOfferCounteredDetailOffer instantiates a new AeAssetNegotiationOfferCounteredDetailOffer object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAeAssetNegotiationOfferCounteredDetailOffer(id string, source string, authorizedBy string, rep CommonAmsRepPointer, amount CommonCurrency, note string, notification CommonAssetNegotiationBaseOfferNotification, counteredBy CommonAssetNegotiationOfferBy) *AeAssetNegotiationOfferCounteredDetailOffer {
	this := AeAssetNegotiationOfferCounteredDetailOffer{}
	this.Id = id
	this.Source = source
	this.AuthorizedBy = authorizedBy
	this.Rep = rep
	this.Amount = amount
	this.Note = note
	this.Notification = notification
	this.CounteredBy = counteredBy
	return &this
}

// NewAeAssetNegotiationOfferCounteredDetailOfferWithDefaults instantiates a new AeAssetNegotiationOfferCounteredDetailOffer object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAeAssetNegotiationOfferCounteredDetailOfferWithDefaults() *AeAssetNegotiationOfferCounteredDetailOffer {
	this := AeAssetNegotiationOfferCounteredDetailOffer{}
	return &this
}

// GetId returns the Id field value
func (o *AeAssetNegotiationOfferCounteredDetailOffer) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AeAssetNegotiationOfferCounteredDetailOffer) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AeAssetNegotiationOfferCounteredDetailOffer) SetId(v string) {
	o.Id = v
}

// GetSource returns the Source field value
func (o *AeAssetNegotiationOfferCounteredDetailOffer) GetSource() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Source
}

// GetSourceOk returns a tuple with the Source field value
// and a boolean to check if the value has been set.
func (o *AeAssetNegotiationOfferCounteredDetailOffer) GetSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Source, true
}

// SetSource sets field value
func (o *AeAssetNegotiationOfferCounteredDetailOffer) SetSource(v string) {
	o.Source = v
}

// GetAuthorizedBy returns the AuthorizedBy field value
func (o *AeAssetNegotiationOfferCounteredDetailOffer) GetAuthorizedBy() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuthorizedBy
}

// GetAuthorizedByOk returns a tuple with the AuthorizedBy field value
// and a boolean to check if the value has been set.
func (o *AeAssetNegotiationOfferCounteredDetailOffer) GetAuthorizedByOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuthorizedBy, true
}

// SetAuthorizedBy sets field value
func (o *AeAssetNegotiationOfferCounteredDetailOffer) SetAuthorizedBy(v string) {
	o.AuthorizedBy = v
}

// GetRep returns the Rep field value
// Deprecated
func (o *AeAssetNegotiationOfferCounteredDetailOffer) GetRep() CommonAmsRepPointer {
	if o == nil {
		var ret CommonAmsRepPointer
		return ret
	}

	return o.Rep
}

// GetRepOk returns a tuple with the Rep field value
// and a boolean to check if the value has been set.
// Deprecated
func (o *AeAssetNegotiationOfferCounteredDetailOffer) GetRepOk() (*CommonAmsRepPointer, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Rep, true
}

// SetRep sets field value
// Deprecated
func (o *AeAssetNegotiationOfferCounteredDetailOffer) SetRep(v CommonAmsRepPointer) {
	o.Rep = v
}

// GetAmount returns the Amount field value
func (o *AeAssetNegotiationOfferCounteredDetailOffer) GetAmount() CommonCurrency {
	if o == nil {
		var ret CommonCurrency
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *AeAssetNegotiationOfferCounteredDetailOffer) GetAmountOk() (*CommonCurrency, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *AeAssetNegotiationOfferCounteredDetailOffer) SetAmount(v CommonCurrency) {
	o.Amount = v
}

// GetNote returns the Note field value
func (o *AeAssetNegotiationOfferCounteredDetailOffer) GetNote() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Note
}

// GetNoteOk returns a tuple with the Note field value
// and a boolean to check if the value has been set.
func (o *AeAssetNegotiationOfferCounteredDetailOffer) GetNoteOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Note, true
}

// SetNote sets field value
func (o *AeAssetNegotiationOfferCounteredDetailOffer) SetNote(v string) {
	o.Note = v
}

// GetNotification returns the Notification field value
func (o *AeAssetNegotiationOfferCounteredDetailOffer) GetNotification() CommonAssetNegotiationBaseOfferNotification {
	if o == nil {
		var ret CommonAssetNegotiationBaseOfferNotification
		return ret
	}

	return o.Notification
}

// GetNotificationOk returns a tuple with the Notification field value
// and a boolean to check if the value has been set.
func (o *AeAssetNegotiationOfferCounteredDetailOffer) GetNotificationOk() (*CommonAssetNegotiationBaseOfferNotification, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Notification, true
}

// SetNotification sets field value
func (o *AeAssetNegotiationOfferCounteredDetailOffer) SetNotification(v CommonAssetNegotiationBaseOfferNotification) {
	o.Notification = v
}

// GetCounteredBy returns the CounteredBy field value
func (o *AeAssetNegotiationOfferCounteredDetailOffer) GetCounteredBy() CommonAssetNegotiationOfferBy {
	if o == nil {
		var ret CommonAssetNegotiationOfferBy
		return ret
	}

	return o.CounteredBy
}

// GetCounteredByOk returns a tuple with the CounteredBy field value
// and a boolean to check if the value has been set.
func (o *AeAssetNegotiationOfferCounteredDetailOffer) GetCounteredByOk() (*CommonAssetNegotiationOfferBy, bool) {
	if o == nil {
		return nil, false
	}
	return &o.CounteredBy, true
}

// SetCounteredBy sets field value
func (o *AeAssetNegotiationOfferCounteredDetailOffer) SetCounteredBy(v CommonAssetNegotiationOfferBy) {
	o.CounteredBy = v
}

func (o AeAssetNegotiationOfferCounteredDetailOffer) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AeAssetNegotiationOfferCounteredDetailOffer) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["source"] = o.Source
	toSerialize["authorized-by"] = o.AuthorizedBy
	toSerialize["rep"] = o.Rep
	toSerialize["amount"] = o.Amount
	toSerialize["note"] = o.Note
	toSerialize["notification"] = o.Notification
	toSerialize["countered-by"] = o.CounteredBy
	return toSerialize, nil
}

func (o *AeAssetNegotiationOfferCounteredDetailOffer) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"source",
		"authorized-by",
		"rep",
		"amount",
		"note",
		"notification",
		"countered-by",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAeAssetNegotiationOfferCounteredDetailOffer := _AeAssetNegotiationOfferCounteredDetailOffer{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAeAssetNegotiationOfferCounteredDetailOffer)

	if err != nil {
		return err
	}

	*o = AeAssetNegotiationOfferCounteredDetailOffer(varAeAssetNegotiationOfferCounteredDetailOffer)

	return err
}

type NullableAeAssetNegotiationOfferCounteredDetailOffer struct {
	value *AeAssetNegotiationOfferCounteredDetailOffer
	isSet bool
}

func (v NullableAeAssetNegotiationOfferCounteredDetailOffer) Get() *AeAssetNegotiationOfferCounteredDetailOffer {
	return v.value
}

func (v *NullableAeAssetNegotiationOfferCounteredDetailOffer) Set(val *AeAssetNegotiationOfferCounteredDetailOffer) {
	v.value = val
	v.isSet = true
}

func (v NullableAeAssetNegotiationOfferCounteredDetailOffer) IsSet() bool {
	return v.isSet
}

func (v *NullableAeAssetNegotiationOfferCounteredDetailOffer) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAeAssetNegotiationOfferCounteredDetailOffer(val *AeAssetNegotiationOfferCounteredDetailOffer) *NullableAeAssetNegotiationOfferCounteredDetailOffer {
	return &NullableAeAssetNegotiationOfferCounteredDetailOffer{value: val, isSet: true}
}

func (v NullableAeAssetNegotiationOfferCounteredDetailOffer) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAeAssetNegotiationOfferCounteredDetailOffer) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


