/*
Edge Event Schemas

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package events

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AeAccountingPaymentSourceUpdatedDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AeAccountingPaymentSourceUpdatedDetail{}

// AeAccountingPaymentSourceUpdatedDetail Notification that the payment source or status for a vehicle has been updated
type AeAccountingPaymentSourceUpdatedDetail struct {
	// Auction Edge unique identifier for an auction.
	AuctionId string `json:"auction-id"`
	// The Vehicle Identification Number(VIN) of the asset.
	Vin string `json:"vin"`
	// The stock number of the asset.
	Stock string `json:"stock"`
	// Simple text describing the prior funding source if any.
	PriorSource NullableString `json:"prior-source"`
	// Simple text describing the current funding source if any.
	CurrentSource NullableString `json:"current-source"`
	PriorStatus *PaymentStatus `json:"prior-status,omitempty"`
	CurrentStatus *PaymentStatus `json:"current-status,omitempty"`
	Initiator *CommonInitiator `json:"initiator,omitempty"`
}

type _AeAccountingPaymentSourceUpdatedDetail AeAccountingPaymentSourceUpdatedDetail

// NewAeAccountingPaymentSourceUpdatedDetail instantiates a new AeAccountingPaymentSourceUpdatedDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAeAccountingPaymentSourceUpdatedDetail(auctionId string, vin string, stock string, priorSource NullableString, currentSource NullableString) *AeAccountingPaymentSourceUpdatedDetail {
	this := AeAccountingPaymentSourceUpdatedDetail{}
	this.AuctionId = auctionId
	this.Vin = vin
	this.Stock = stock
	this.PriorSource = priorSource
	this.CurrentSource = currentSource
	return &this
}

// NewAeAccountingPaymentSourceUpdatedDetailWithDefaults instantiates a new AeAccountingPaymentSourceUpdatedDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAeAccountingPaymentSourceUpdatedDetailWithDefaults() *AeAccountingPaymentSourceUpdatedDetail {
	this := AeAccountingPaymentSourceUpdatedDetail{}
	return &this
}

// GetAuctionId returns the AuctionId field value
func (o *AeAccountingPaymentSourceUpdatedDetail) GetAuctionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuctionId
}

// GetAuctionIdOk returns a tuple with the AuctionId field value
// and a boolean to check if the value has been set.
func (o *AeAccountingPaymentSourceUpdatedDetail) GetAuctionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuctionId, true
}

// SetAuctionId sets field value
func (o *AeAccountingPaymentSourceUpdatedDetail) SetAuctionId(v string) {
	o.AuctionId = v
}

// GetVin returns the Vin field value
func (o *AeAccountingPaymentSourceUpdatedDetail) GetVin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Vin
}

// GetVinOk returns a tuple with the Vin field value
// and a boolean to check if the value has been set.
func (o *AeAccountingPaymentSourceUpdatedDetail) GetVinOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vin, true
}

// SetVin sets field value
func (o *AeAccountingPaymentSourceUpdatedDetail) SetVin(v string) {
	o.Vin = v
}

// GetStock returns the Stock field value
func (o *AeAccountingPaymentSourceUpdatedDetail) GetStock() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Stock
}

// GetStockOk returns a tuple with the Stock field value
// and a boolean to check if the value has been set.
func (o *AeAccountingPaymentSourceUpdatedDetail) GetStockOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Stock, true
}

// SetStock sets field value
func (o *AeAccountingPaymentSourceUpdatedDetail) SetStock(v string) {
	o.Stock = v
}

// GetPriorSource returns the PriorSource field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AeAccountingPaymentSourceUpdatedDetail) GetPriorSource() string {
	if o == nil || o.PriorSource.Get() == nil {
		var ret string
		return ret
	}

	return *o.PriorSource.Get()
}

// GetPriorSourceOk returns a tuple with the PriorSource field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AeAccountingPaymentSourceUpdatedDetail) GetPriorSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.PriorSource.Get(), o.PriorSource.IsSet()
}

// SetPriorSource sets field value
func (o *AeAccountingPaymentSourceUpdatedDetail) SetPriorSource(v string) {
	o.PriorSource.Set(&v)
}

// GetCurrentSource returns the CurrentSource field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AeAccountingPaymentSourceUpdatedDetail) GetCurrentSource() string {
	if o == nil || o.CurrentSource.Get() == nil {
		var ret string
		return ret
	}

	return *o.CurrentSource.Get()
}

// GetCurrentSourceOk returns a tuple with the CurrentSource field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AeAccountingPaymentSourceUpdatedDetail) GetCurrentSourceOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.CurrentSource.Get(), o.CurrentSource.IsSet()
}

// SetCurrentSource sets field value
func (o *AeAccountingPaymentSourceUpdatedDetail) SetCurrentSource(v string) {
	o.CurrentSource.Set(&v)
}

// GetPriorStatus returns the PriorStatus field value if set, zero value otherwise.
func (o *AeAccountingPaymentSourceUpdatedDetail) GetPriorStatus() PaymentStatus {
	if o == nil || IsNil(o.PriorStatus) {
		var ret PaymentStatus
		return ret
	}
	return *o.PriorStatus
}

// GetPriorStatusOk returns a tuple with the PriorStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAccountingPaymentSourceUpdatedDetail) GetPriorStatusOk() (*PaymentStatus, bool) {
	if o == nil || IsNil(o.PriorStatus) {
		return nil, false
	}
	return o.PriorStatus, true
}

// HasPriorStatus returns a boolean if a field has been set.
func (o *AeAccountingPaymentSourceUpdatedDetail) HasPriorStatus() bool {
	if o != nil && !IsNil(o.PriorStatus) {
		return true
	}

	return false
}

// SetPriorStatus gets a reference to the given PaymentStatus and assigns it to the PriorStatus field.
func (o *AeAccountingPaymentSourceUpdatedDetail) SetPriorStatus(v PaymentStatus) {
	o.PriorStatus = &v
}

// GetCurrentStatus returns the CurrentStatus field value if set, zero value otherwise.
func (o *AeAccountingPaymentSourceUpdatedDetail) GetCurrentStatus() PaymentStatus {
	if o == nil || IsNil(o.CurrentStatus) {
		var ret PaymentStatus
		return ret
	}
	return *o.CurrentStatus
}

// GetCurrentStatusOk returns a tuple with the CurrentStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAccountingPaymentSourceUpdatedDetail) GetCurrentStatusOk() (*PaymentStatus, bool) {
	if o == nil || IsNil(o.CurrentStatus) {
		return nil, false
	}
	return o.CurrentStatus, true
}

// HasCurrentStatus returns a boolean if a field has been set.
func (o *AeAccountingPaymentSourceUpdatedDetail) HasCurrentStatus() bool {
	if o != nil && !IsNil(o.CurrentStatus) {
		return true
	}

	return false
}

// SetCurrentStatus gets a reference to the given PaymentStatus and assigns it to the CurrentStatus field.
func (o *AeAccountingPaymentSourceUpdatedDetail) SetCurrentStatus(v PaymentStatus) {
	o.CurrentStatus = &v
}

// GetInitiator returns the Initiator field value if set, zero value otherwise.
func (o *AeAccountingPaymentSourceUpdatedDetail) GetInitiator() CommonInitiator {
	if o == nil || IsNil(o.Initiator) {
		var ret CommonInitiator
		return ret
	}
	return *o.Initiator
}

// GetInitiatorOk returns a tuple with the Initiator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAccountingPaymentSourceUpdatedDetail) GetInitiatorOk() (*CommonInitiator, bool) {
	if o == nil || IsNil(o.Initiator) {
		return nil, false
	}
	return o.Initiator, true
}

// HasInitiator returns a boolean if a field has been set.
func (o *AeAccountingPaymentSourceUpdatedDetail) HasInitiator() bool {
	if o != nil && !IsNil(o.Initiator) {
		return true
	}

	return false
}

// SetInitiator gets a reference to the given CommonInitiator and assigns it to the Initiator field.
func (o *AeAccountingPaymentSourceUpdatedDetail) SetInitiator(v CommonInitiator) {
	o.Initiator = &v
}

func (o AeAccountingPaymentSourceUpdatedDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AeAccountingPaymentSourceUpdatedDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["auction-id"] = o.AuctionId
	toSerialize["vin"] = o.Vin
	toSerialize["stock"] = o.Stock
	toSerialize["prior-source"] = o.PriorSource.Get()
	toSerialize["current-source"] = o.CurrentSource.Get()
	if !IsNil(o.PriorStatus) {
		toSerialize["prior-status"] = o.PriorStatus
	}
	if !IsNil(o.CurrentStatus) {
		toSerialize["current-status"] = o.CurrentStatus
	}
	if !IsNil(o.Initiator) {
		toSerialize["initiator"] = o.Initiator
	}
	return toSerialize, nil
}

func (o *AeAccountingPaymentSourceUpdatedDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"auction-id",
		"vin",
		"stock",
		"prior-source",
		"current-source",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAeAccountingPaymentSourceUpdatedDetail := _AeAccountingPaymentSourceUpdatedDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAeAccountingPaymentSourceUpdatedDetail)

	if err != nil {
		return err
	}

	*o = AeAccountingPaymentSourceUpdatedDetail(varAeAccountingPaymentSourceUpdatedDetail)

	return err
}

type NullableAeAccountingPaymentSourceUpdatedDetail struct {
	value *AeAccountingPaymentSourceUpdatedDetail
	isSet bool
}

func (v NullableAeAccountingPaymentSourceUpdatedDetail) Get() *AeAccountingPaymentSourceUpdatedDetail {
	return v.value
}

func (v *NullableAeAccountingPaymentSourceUpdatedDetail) Set(val *AeAccountingPaymentSourceUpdatedDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableAeAccountingPaymentSourceUpdatedDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableAeAccountingPaymentSourceUpdatedDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAeAccountingPaymentSourceUpdatedDetail(val *AeAccountingPaymentSourceUpdatedDetail) *NullableAeAccountingPaymentSourceUpdatedDetail {
	return &NullableAeAccountingPaymentSourceUpdatedDetail{value: val, isSet: true}
}

func (v NullableAeAccountingPaymentSourceUpdatedDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAeAccountingPaymentSourceUpdatedDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


