/*
Edge Event Schemas

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package events

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AeAssetNegotiationNoteAddedDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AeAssetNegotiationNoteAddedDetail{}

// AeAssetNegotiationNoteAddedDetail emitted by the negotiation service when a note is added to a negotiation.
type AeAssetNegotiationNoteAddedDetail struct {
	// Auction Edge unique identifier for an auction.
	AuctionId string `json:"auction-id"`
	// the unique identifier of the negotiation
	NegotiationId string `json:"negotiation-id"`
	Note AeAssetNegotiationNoteAddedDetailNote `json:"note"`
	Initiator *CommonInitiator `json:"initiator,omitempty"`
}

type _AeAssetNegotiationNoteAddedDetail AeAssetNegotiationNoteAddedDetail

// NewAeAssetNegotiationNoteAddedDetail instantiates a new AeAssetNegotiationNoteAddedDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAeAssetNegotiationNoteAddedDetail(auctionId string, negotiationId string, note AeAssetNegotiationNoteAddedDetailNote) *AeAssetNegotiationNoteAddedDetail {
	this := AeAssetNegotiationNoteAddedDetail{}
	this.AuctionId = auctionId
	this.NegotiationId = negotiationId
	this.Note = note
	return &this
}

// NewAeAssetNegotiationNoteAddedDetailWithDefaults instantiates a new AeAssetNegotiationNoteAddedDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAeAssetNegotiationNoteAddedDetailWithDefaults() *AeAssetNegotiationNoteAddedDetail {
	this := AeAssetNegotiationNoteAddedDetail{}
	return &this
}

// GetAuctionId returns the AuctionId field value
func (o *AeAssetNegotiationNoteAddedDetail) GetAuctionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuctionId
}

// GetAuctionIdOk returns a tuple with the AuctionId field value
// and a boolean to check if the value has been set.
func (o *AeAssetNegotiationNoteAddedDetail) GetAuctionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuctionId, true
}

// SetAuctionId sets field value
func (o *AeAssetNegotiationNoteAddedDetail) SetAuctionId(v string) {
	o.AuctionId = v
}

// GetNegotiationId returns the NegotiationId field value
func (o *AeAssetNegotiationNoteAddedDetail) GetNegotiationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NegotiationId
}

// GetNegotiationIdOk returns a tuple with the NegotiationId field value
// and a boolean to check if the value has been set.
func (o *AeAssetNegotiationNoteAddedDetail) GetNegotiationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NegotiationId, true
}

// SetNegotiationId sets field value
func (o *AeAssetNegotiationNoteAddedDetail) SetNegotiationId(v string) {
	o.NegotiationId = v
}

// GetNote returns the Note field value
func (o *AeAssetNegotiationNoteAddedDetail) GetNote() AeAssetNegotiationNoteAddedDetailNote {
	if o == nil {
		var ret AeAssetNegotiationNoteAddedDetailNote
		return ret
	}

	return o.Note
}

// GetNoteOk returns a tuple with the Note field value
// and a boolean to check if the value has been set.
func (o *AeAssetNegotiationNoteAddedDetail) GetNoteOk() (*AeAssetNegotiationNoteAddedDetailNote, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Note, true
}

// SetNote sets field value
func (o *AeAssetNegotiationNoteAddedDetail) SetNote(v AeAssetNegotiationNoteAddedDetailNote) {
	o.Note = v
}

// GetInitiator returns the Initiator field value if set, zero value otherwise.
func (o *AeAssetNegotiationNoteAddedDetail) GetInitiator() CommonInitiator {
	if o == nil || IsNil(o.Initiator) {
		var ret CommonInitiator
		return ret
	}
	return *o.Initiator
}

// GetInitiatorOk returns a tuple with the Initiator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAssetNegotiationNoteAddedDetail) GetInitiatorOk() (*CommonInitiator, bool) {
	if o == nil || IsNil(o.Initiator) {
		return nil, false
	}
	return o.Initiator, true
}

// HasInitiator returns a boolean if a field has been set.
func (o *AeAssetNegotiationNoteAddedDetail) HasInitiator() bool {
	if o != nil && !IsNil(o.Initiator) {
		return true
	}

	return false
}

// SetInitiator gets a reference to the given CommonInitiator and assigns it to the Initiator field.
func (o *AeAssetNegotiationNoteAddedDetail) SetInitiator(v CommonInitiator) {
	o.Initiator = &v
}

func (o AeAssetNegotiationNoteAddedDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AeAssetNegotiationNoteAddedDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["auction-id"] = o.AuctionId
	toSerialize["negotiation-id"] = o.NegotiationId
	toSerialize["note"] = o.Note
	if !IsNil(o.Initiator) {
		toSerialize["initiator"] = o.Initiator
	}
	return toSerialize, nil
}

func (o *AeAssetNegotiationNoteAddedDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"auction-id",
		"negotiation-id",
		"note",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAeAssetNegotiationNoteAddedDetail := _AeAssetNegotiationNoteAddedDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAeAssetNegotiationNoteAddedDetail)

	if err != nil {
		return err
	}

	*o = AeAssetNegotiationNoteAddedDetail(varAeAssetNegotiationNoteAddedDetail)

	return err
}

type NullableAeAssetNegotiationNoteAddedDetail struct {
	value *AeAssetNegotiationNoteAddedDetail
	isSet bool
}

func (v NullableAeAssetNegotiationNoteAddedDetail) Get() *AeAssetNegotiationNoteAddedDetail {
	return v.value
}

func (v *NullableAeAssetNegotiationNoteAddedDetail) Set(val *AeAssetNegotiationNoteAddedDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableAeAssetNegotiationNoteAddedDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableAeAssetNegotiationNoteAddedDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAeAssetNegotiationNoteAddedDetail(val *AeAssetNegotiationNoteAddedDetail) *NullableAeAssetNegotiationNoteAddedDetail {
	return &NullableAeAssetNegotiationNoteAddedDetail{value: val, isSet: true}
}

func (v NullableAeAssetNegotiationNoteAddedDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAeAssetNegotiationNoteAddedDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


