/*
Edge Event Schemas

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package events

import (
	"encoding/json"
	"fmt"
)

// checks if the AeAccountRepresentativeUpsertedAmsDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AeAccountRepresentativeUpsertedAmsDetail{}

// AeAccountRepresentativeUpsertedAmsDetail Upserted data for an representative in the AMS
type AeAccountRepresentativeUpsertedAmsDetail struct {
	// The representative id an AMS account
	Id string `json:"id"`
	// The Auction Access ID of the AMS Representative account.
	AaId NullableString `json:"aa-id"`
	// Rep number as denoted in ASI, AOS to use same value as representative-id
	RepNumber *float32 `json:"rep-number,omitempty"`
	// Auction Edge unique identifier for an auction.
	AuctionId string `json:"auction-id"`
	// Source's unique identifier for account
	AccountId *string `json:"account-id,omitempty"`
	PersonInfo *CommonAmsPersonInfo `json:"person-info,omitempty"`
	// Any notes on representative
	InternalNotes *string `json:"internal-notes,omitempty"`
	// True if representative is allowed to buy a vehicle, false if not
	CanBuy *bool `json:"can-buy,omitempty"`
	Initiator *CommonInitiator `json:"initiator,omitempty"`
	AdditionalProperties map[string]interface{}
}

type _AeAccountRepresentativeUpsertedAmsDetail AeAccountRepresentativeUpsertedAmsDetail

// NewAeAccountRepresentativeUpsertedAmsDetail instantiates a new AeAccountRepresentativeUpsertedAmsDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAeAccountRepresentativeUpsertedAmsDetail(id string, aaId NullableString, auctionId string) *AeAccountRepresentativeUpsertedAmsDetail {
	this := AeAccountRepresentativeUpsertedAmsDetail{}
	this.Id = id
	this.AaId = aaId
	this.AuctionId = auctionId
	return &this
}

// NewAeAccountRepresentativeUpsertedAmsDetailWithDefaults instantiates a new AeAccountRepresentativeUpsertedAmsDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAeAccountRepresentativeUpsertedAmsDetailWithDefaults() *AeAccountRepresentativeUpsertedAmsDetail {
	this := AeAccountRepresentativeUpsertedAmsDetail{}
	return &this
}

// GetId returns the Id field value
func (o *AeAccountRepresentativeUpsertedAmsDetail) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AeAccountRepresentativeUpsertedAmsDetail) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AeAccountRepresentativeUpsertedAmsDetail) SetId(v string) {
	o.Id = v
}

// GetAaId returns the AaId field value
// If the value is explicit nil, the zero value for string will be returned
func (o *AeAccountRepresentativeUpsertedAmsDetail) GetAaId() string {
	if o == nil || o.AaId.Get() == nil {
		var ret string
		return ret
	}

	return *o.AaId.Get()
}

// GetAaIdOk returns a tuple with the AaId field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AeAccountRepresentativeUpsertedAmsDetail) GetAaIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.AaId.Get(), o.AaId.IsSet()
}

// SetAaId sets field value
func (o *AeAccountRepresentativeUpsertedAmsDetail) SetAaId(v string) {
	o.AaId.Set(&v)
}

// GetRepNumber returns the RepNumber field value if set, zero value otherwise.
func (o *AeAccountRepresentativeUpsertedAmsDetail) GetRepNumber() float32 {
	if o == nil || IsNil(o.RepNumber) {
		var ret float32
		return ret
	}
	return *o.RepNumber
}

// GetRepNumberOk returns a tuple with the RepNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAccountRepresentativeUpsertedAmsDetail) GetRepNumberOk() (*float32, bool) {
	if o == nil || IsNil(o.RepNumber) {
		return nil, false
	}
	return o.RepNumber, true
}

// HasRepNumber returns a boolean if a field has been set.
func (o *AeAccountRepresentativeUpsertedAmsDetail) HasRepNumber() bool {
	if o != nil && !IsNil(o.RepNumber) {
		return true
	}

	return false
}

// SetRepNumber gets a reference to the given float32 and assigns it to the RepNumber field.
func (o *AeAccountRepresentativeUpsertedAmsDetail) SetRepNumber(v float32) {
	o.RepNumber = &v
}

// GetAuctionId returns the AuctionId field value
func (o *AeAccountRepresentativeUpsertedAmsDetail) GetAuctionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuctionId
}

// GetAuctionIdOk returns a tuple with the AuctionId field value
// and a boolean to check if the value has been set.
func (o *AeAccountRepresentativeUpsertedAmsDetail) GetAuctionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuctionId, true
}

// SetAuctionId sets field value
func (o *AeAccountRepresentativeUpsertedAmsDetail) SetAuctionId(v string) {
	o.AuctionId = v
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *AeAccountRepresentativeUpsertedAmsDetail) GetAccountId() string {
	if o == nil || IsNil(o.AccountId) {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAccountRepresentativeUpsertedAmsDetail) GetAccountIdOk() (*string, bool) {
	if o == nil || IsNil(o.AccountId) {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *AeAccountRepresentativeUpsertedAmsDetail) HasAccountId() bool {
	if o != nil && !IsNil(o.AccountId) {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *AeAccountRepresentativeUpsertedAmsDetail) SetAccountId(v string) {
	o.AccountId = &v
}

// GetPersonInfo returns the PersonInfo field value if set, zero value otherwise.
func (o *AeAccountRepresentativeUpsertedAmsDetail) GetPersonInfo() CommonAmsPersonInfo {
	if o == nil || IsNil(o.PersonInfo) {
		var ret CommonAmsPersonInfo
		return ret
	}
	return *o.PersonInfo
}

// GetPersonInfoOk returns a tuple with the PersonInfo field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAccountRepresentativeUpsertedAmsDetail) GetPersonInfoOk() (*CommonAmsPersonInfo, bool) {
	if o == nil || IsNil(o.PersonInfo) {
		return nil, false
	}
	return o.PersonInfo, true
}

// HasPersonInfo returns a boolean if a field has been set.
func (o *AeAccountRepresentativeUpsertedAmsDetail) HasPersonInfo() bool {
	if o != nil && !IsNil(o.PersonInfo) {
		return true
	}

	return false
}

// SetPersonInfo gets a reference to the given CommonAmsPersonInfo and assigns it to the PersonInfo field.
func (o *AeAccountRepresentativeUpsertedAmsDetail) SetPersonInfo(v CommonAmsPersonInfo) {
	o.PersonInfo = &v
}

// GetInternalNotes returns the InternalNotes field value if set, zero value otherwise.
func (o *AeAccountRepresentativeUpsertedAmsDetail) GetInternalNotes() string {
	if o == nil || IsNil(o.InternalNotes) {
		var ret string
		return ret
	}
	return *o.InternalNotes
}

// GetInternalNotesOk returns a tuple with the InternalNotes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAccountRepresentativeUpsertedAmsDetail) GetInternalNotesOk() (*string, bool) {
	if o == nil || IsNil(o.InternalNotes) {
		return nil, false
	}
	return o.InternalNotes, true
}

// HasInternalNotes returns a boolean if a field has been set.
func (o *AeAccountRepresentativeUpsertedAmsDetail) HasInternalNotes() bool {
	if o != nil && !IsNil(o.InternalNotes) {
		return true
	}

	return false
}

// SetInternalNotes gets a reference to the given string and assigns it to the InternalNotes field.
func (o *AeAccountRepresentativeUpsertedAmsDetail) SetInternalNotes(v string) {
	o.InternalNotes = &v
}

// GetCanBuy returns the CanBuy field value if set, zero value otherwise.
func (o *AeAccountRepresentativeUpsertedAmsDetail) GetCanBuy() bool {
	if o == nil || IsNil(o.CanBuy) {
		var ret bool
		return ret
	}
	return *o.CanBuy
}

// GetCanBuyOk returns a tuple with the CanBuy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAccountRepresentativeUpsertedAmsDetail) GetCanBuyOk() (*bool, bool) {
	if o == nil || IsNil(o.CanBuy) {
		return nil, false
	}
	return o.CanBuy, true
}

// HasCanBuy returns a boolean if a field has been set.
func (o *AeAccountRepresentativeUpsertedAmsDetail) HasCanBuy() bool {
	if o != nil && !IsNil(o.CanBuy) {
		return true
	}

	return false
}

// SetCanBuy gets a reference to the given bool and assigns it to the CanBuy field.
func (o *AeAccountRepresentativeUpsertedAmsDetail) SetCanBuy(v bool) {
	o.CanBuy = &v
}

// GetInitiator returns the Initiator field value if set, zero value otherwise.
func (o *AeAccountRepresentativeUpsertedAmsDetail) GetInitiator() CommonInitiator {
	if o == nil || IsNil(o.Initiator) {
		var ret CommonInitiator
		return ret
	}
	return *o.Initiator
}

// GetInitiatorOk returns a tuple with the Initiator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAccountRepresentativeUpsertedAmsDetail) GetInitiatorOk() (*CommonInitiator, bool) {
	if o == nil || IsNil(o.Initiator) {
		return nil, false
	}
	return o.Initiator, true
}

// HasInitiator returns a boolean if a field has been set.
func (o *AeAccountRepresentativeUpsertedAmsDetail) HasInitiator() bool {
	if o != nil && !IsNil(o.Initiator) {
		return true
	}

	return false
}

// SetInitiator gets a reference to the given CommonInitiator and assigns it to the Initiator field.
func (o *AeAccountRepresentativeUpsertedAmsDetail) SetInitiator(v CommonInitiator) {
	o.Initiator = &v
}

func (o AeAccountRepresentativeUpsertedAmsDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AeAccountRepresentativeUpsertedAmsDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["aa-id"] = o.AaId.Get()
	if !IsNil(o.RepNumber) {
		toSerialize["rep-number"] = o.RepNumber
	}
	toSerialize["auction-id"] = o.AuctionId
	if !IsNil(o.AccountId) {
		toSerialize["account-id"] = o.AccountId
	}
	if !IsNil(o.PersonInfo) {
		toSerialize["person-info"] = o.PersonInfo
	}
	if !IsNil(o.InternalNotes) {
		toSerialize["internal-notes"] = o.InternalNotes
	}
	if !IsNil(o.CanBuy) {
		toSerialize["can-buy"] = o.CanBuy
	}
	if !IsNil(o.Initiator) {
		toSerialize["initiator"] = o.Initiator
	}

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AeAccountRepresentativeUpsertedAmsDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"aa-id",
		"auction-id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAeAccountRepresentativeUpsertedAmsDetail := _AeAccountRepresentativeUpsertedAmsDetail{}

	err = json.Unmarshal(data, &varAeAccountRepresentativeUpsertedAmsDetail)

	if err != nil {
		return err
	}

	*o = AeAccountRepresentativeUpsertedAmsDetail(varAeAccountRepresentativeUpsertedAmsDetail)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "aa-id")
		delete(additionalProperties, "rep-number")
		delete(additionalProperties, "auction-id")
		delete(additionalProperties, "account-id")
		delete(additionalProperties, "person-info")
		delete(additionalProperties, "internal-notes")
		delete(additionalProperties, "can-buy")
		delete(additionalProperties, "initiator")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAeAccountRepresentativeUpsertedAmsDetail struct {
	value *AeAccountRepresentativeUpsertedAmsDetail
	isSet bool
}

func (v NullableAeAccountRepresentativeUpsertedAmsDetail) Get() *AeAccountRepresentativeUpsertedAmsDetail {
	return v.value
}

func (v *NullableAeAccountRepresentativeUpsertedAmsDetail) Set(val *AeAccountRepresentativeUpsertedAmsDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableAeAccountRepresentativeUpsertedAmsDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableAeAccountRepresentativeUpsertedAmsDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAeAccountRepresentativeUpsertedAmsDetail(val *AeAccountRepresentativeUpsertedAmsDetail) *NullableAeAccountRepresentativeUpsertedAmsDetail {
	return &NullableAeAccountRepresentativeUpsertedAmsDetail{value: val, isSet: true}
}

func (v NullableAeAccountRepresentativeUpsertedAmsDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAeAccountRepresentativeUpsertedAmsDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


