/*
Edge Event Schemas

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package events

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the AeAssetNotSoldDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AeAssetNotSoldDetail{}

// AeAssetNotSoldDetail Vehicle ran in a sale, but did not sell
type AeAssetNotSoldDetail struct {
	// Auction Edge unique identifier for an auction.
	AuctionId string `json:"auction-id"`
	Asset CommonAmsAssetPointer `json:"asset"`
	// Uniquie identifier for a sale listing.
	SaleListingId string `json:"sale-listing-id"`
	// The updated date time of the gatepass status
	UpdatedAt time.Time `json:"updated-at"`
	Initiator CommonInitiator `json:"initiator"`
}

type _AeAssetNotSoldDetail AeAssetNotSoldDetail

// NewAeAssetNotSoldDetail instantiates a new AeAssetNotSoldDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAeAssetNotSoldDetail(auctionId string, asset CommonAmsAssetPointer, saleListingId string, updatedAt time.Time, initiator CommonInitiator) *AeAssetNotSoldDetail {
	this := AeAssetNotSoldDetail{}
	this.AuctionId = auctionId
	this.Asset = asset
	this.SaleListingId = saleListingId
	this.UpdatedAt = updatedAt
	this.Initiator = initiator
	return &this
}

// NewAeAssetNotSoldDetailWithDefaults instantiates a new AeAssetNotSoldDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAeAssetNotSoldDetailWithDefaults() *AeAssetNotSoldDetail {
	this := AeAssetNotSoldDetail{}
	return &this
}

// GetAuctionId returns the AuctionId field value
func (o *AeAssetNotSoldDetail) GetAuctionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuctionId
}

// GetAuctionIdOk returns a tuple with the AuctionId field value
// and a boolean to check if the value has been set.
func (o *AeAssetNotSoldDetail) GetAuctionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuctionId, true
}

// SetAuctionId sets field value
func (o *AeAssetNotSoldDetail) SetAuctionId(v string) {
	o.AuctionId = v
}

// GetAsset returns the Asset field value
func (o *AeAssetNotSoldDetail) GetAsset() CommonAmsAssetPointer {
	if o == nil {
		var ret CommonAmsAssetPointer
		return ret
	}

	return o.Asset
}

// GetAssetOk returns a tuple with the Asset field value
// and a boolean to check if the value has been set.
func (o *AeAssetNotSoldDetail) GetAssetOk() (*CommonAmsAssetPointer, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asset, true
}

// SetAsset sets field value
func (o *AeAssetNotSoldDetail) SetAsset(v CommonAmsAssetPointer) {
	o.Asset = v
}

// GetSaleListingId returns the SaleListingId field value
func (o *AeAssetNotSoldDetail) GetSaleListingId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SaleListingId
}

// GetSaleListingIdOk returns a tuple with the SaleListingId field value
// and a boolean to check if the value has been set.
func (o *AeAssetNotSoldDetail) GetSaleListingIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SaleListingId, true
}

// SetSaleListingId sets field value
func (o *AeAssetNotSoldDetail) SetSaleListingId(v string) {
	o.SaleListingId = v
}

// GetUpdatedAt returns the UpdatedAt field value
func (o *AeAssetNotSoldDetail) GetUpdatedAt() time.Time {
	if o == nil {
		var ret time.Time
		return ret
	}

	return o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value
// and a boolean to check if the value has been set.
func (o *AeAssetNotSoldDetail) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil {
		return nil, false
	}
	return &o.UpdatedAt, true
}

// SetUpdatedAt sets field value
func (o *AeAssetNotSoldDetail) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = v
}

// GetInitiator returns the Initiator field value
func (o *AeAssetNotSoldDetail) GetInitiator() CommonInitiator {
	if o == nil {
		var ret CommonInitiator
		return ret
	}

	return o.Initiator
}

// GetInitiatorOk returns a tuple with the Initiator field value
// and a boolean to check if the value has been set.
func (o *AeAssetNotSoldDetail) GetInitiatorOk() (*CommonInitiator, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Initiator, true
}

// SetInitiator sets field value
func (o *AeAssetNotSoldDetail) SetInitiator(v CommonInitiator) {
	o.Initiator = v
}

func (o AeAssetNotSoldDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AeAssetNotSoldDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["auction-id"] = o.AuctionId
	toSerialize["asset"] = o.Asset
	toSerialize["sale-listing-id"] = o.SaleListingId
	toSerialize["updated-at"] = o.UpdatedAt
	toSerialize["initiator"] = o.Initiator
	return toSerialize, nil
}

func (o *AeAssetNotSoldDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"auction-id",
		"asset",
		"sale-listing-id",
		"updated-at",
		"initiator",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAeAssetNotSoldDetail := _AeAssetNotSoldDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAeAssetNotSoldDetail)

	if err != nil {
		return err
	}

	*o = AeAssetNotSoldDetail(varAeAssetNotSoldDetail)

	return err
}

type NullableAeAssetNotSoldDetail struct {
	value *AeAssetNotSoldDetail
	isSet bool
}

func (v NullableAeAssetNotSoldDetail) Get() *AeAssetNotSoldDetail {
	return v.value
}

func (v *NullableAeAssetNotSoldDetail) Set(val *AeAssetNotSoldDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableAeAssetNotSoldDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableAeAssetNotSoldDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAeAssetNotSoldDetail(val *AeAssetNotSoldDetail) *NullableAeAssetNotSoldDetail {
	return &NullableAeAssetNotSoldDetail{value: val, isSet: true}
}

func (v NullableAeAssetNotSoldDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAeAssetNotSoldDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


