/*
Edge Event Schemas

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package events

import (
	"encoding/json"
	"time"
	"bytes"
	"fmt"
)

// checks if the AeAssetDealOfferMadeDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AeAssetDealOfferMadeDetail{}

// AeAssetDealOfferMadeDetail Offer made on asset.
type AeAssetDealOfferMadeDetail struct {
	// Auction Edge unique identifier for an auction.
	AuctionId string `json:"auction-id"`
	Asset *CommonAmsAssetPointer `json:"asset,omitempty"`
	// Unique id for a deal
	DealId *string `json:"deal-id,omitempty"`
	// The Vehicle Identification Number(VIN) of the asset.
	Vin string `json:"vin"`
	// The stock number of the asset.
	Stock string `json:"stock"`
	Seller CommonAmsAccountPointer `json:"seller"`
	Buyer CommonAmsAccountPointer `json:"buyer"`
	// The sale date of the deal.
	SaleDate string `json:"sale-date"`
	// The lane the asset was in when deal made.
	Lane string `json:"lane"`
	// The lot the asset was in when deal made.
	Lot string `json:"lot"`
	// The amount the asset sold for.
	Amount float32 `json:"amount"`
	// The updated date time of the gatepass status
	UpdatedAt *time.Time `json:"updated-at,omitempty"`
	Initiator *CommonInitiator `json:"initiator,omitempty"`
}

type _AeAssetDealOfferMadeDetail AeAssetDealOfferMadeDetail

// NewAeAssetDealOfferMadeDetail instantiates a new AeAssetDealOfferMadeDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAeAssetDealOfferMadeDetail(auctionId string, vin string, stock string, seller CommonAmsAccountPointer, buyer CommonAmsAccountPointer, saleDate string, lane string, lot string, amount float32) *AeAssetDealOfferMadeDetail {
	this := AeAssetDealOfferMadeDetail{}
	this.AuctionId = auctionId
	this.Vin = vin
	this.Stock = stock
	this.Seller = seller
	this.Buyer = buyer
	this.SaleDate = saleDate
	this.Lane = lane
	this.Lot = lot
	this.Amount = amount
	return &this
}

// NewAeAssetDealOfferMadeDetailWithDefaults instantiates a new AeAssetDealOfferMadeDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAeAssetDealOfferMadeDetailWithDefaults() *AeAssetDealOfferMadeDetail {
	this := AeAssetDealOfferMadeDetail{}
	return &this
}

// GetAuctionId returns the AuctionId field value
func (o *AeAssetDealOfferMadeDetail) GetAuctionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuctionId
}

// GetAuctionIdOk returns a tuple with the AuctionId field value
// and a boolean to check if the value has been set.
func (o *AeAssetDealOfferMadeDetail) GetAuctionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuctionId, true
}

// SetAuctionId sets field value
func (o *AeAssetDealOfferMadeDetail) SetAuctionId(v string) {
	o.AuctionId = v
}

// GetAsset returns the Asset field value if set, zero value otherwise.
func (o *AeAssetDealOfferMadeDetail) GetAsset() CommonAmsAssetPointer {
	if o == nil || IsNil(o.Asset) {
		var ret CommonAmsAssetPointer
		return ret
	}
	return *o.Asset
}

// GetAssetOk returns a tuple with the Asset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAssetDealOfferMadeDetail) GetAssetOk() (*CommonAmsAssetPointer, bool) {
	if o == nil || IsNil(o.Asset) {
		return nil, false
	}
	return o.Asset, true
}

// HasAsset returns a boolean if a field has been set.
func (o *AeAssetDealOfferMadeDetail) HasAsset() bool {
	if o != nil && !IsNil(o.Asset) {
		return true
	}

	return false
}

// SetAsset gets a reference to the given CommonAmsAssetPointer and assigns it to the Asset field.
func (o *AeAssetDealOfferMadeDetail) SetAsset(v CommonAmsAssetPointer) {
	o.Asset = &v
}

// GetDealId returns the DealId field value if set, zero value otherwise.
func (o *AeAssetDealOfferMadeDetail) GetDealId() string {
	if o == nil || IsNil(o.DealId) {
		var ret string
		return ret
	}
	return *o.DealId
}

// GetDealIdOk returns a tuple with the DealId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAssetDealOfferMadeDetail) GetDealIdOk() (*string, bool) {
	if o == nil || IsNil(o.DealId) {
		return nil, false
	}
	return o.DealId, true
}

// HasDealId returns a boolean if a field has been set.
func (o *AeAssetDealOfferMadeDetail) HasDealId() bool {
	if o != nil && !IsNil(o.DealId) {
		return true
	}

	return false
}

// SetDealId gets a reference to the given string and assigns it to the DealId field.
func (o *AeAssetDealOfferMadeDetail) SetDealId(v string) {
	o.DealId = &v
}

// GetVin returns the Vin field value
func (o *AeAssetDealOfferMadeDetail) GetVin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Vin
}

// GetVinOk returns a tuple with the Vin field value
// and a boolean to check if the value has been set.
func (o *AeAssetDealOfferMadeDetail) GetVinOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vin, true
}

// SetVin sets field value
func (o *AeAssetDealOfferMadeDetail) SetVin(v string) {
	o.Vin = v
}

// GetStock returns the Stock field value
func (o *AeAssetDealOfferMadeDetail) GetStock() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Stock
}

// GetStockOk returns a tuple with the Stock field value
// and a boolean to check if the value has been set.
func (o *AeAssetDealOfferMadeDetail) GetStockOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Stock, true
}

// SetStock sets field value
func (o *AeAssetDealOfferMadeDetail) SetStock(v string) {
	o.Stock = v
}

// GetSeller returns the Seller field value
func (o *AeAssetDealOfferMadeDetail) GetSeller() CommonAmsAccountPointer {
	if o == nil {
		var ret CommonAmsAccountPointer
		return ret
	}

	return o.Seller
}

// GetSellerOk returns a tuple with the Seller field value
// and a boolean to check if the value has been set.
func (o *AeAssetDealOfferMadeDetail) GetSellerOk() (*CommonAmsAccountPointer, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Seller, true
}

// SetSeller sets field value
func (o *AeAssetDealOfferMadeDetail) SetSeller(v CommonAmsAccountPointer) {
	o.Seller = v
}

// GetBuyer returns the Buyer field value
func (o *AeAssetDealOfferMadeDetail) GetBuyer() CommonAmsAccountPointer {
	if o == nil {
		var ret CommonAmsAccountPointer
		return ret
	}

	return o.Buyer
}

// GetBuyerOk returns a tuple with the Buyer field value
// and a boolean to check if the value has been set.
func (o *AeAssetDealOfferMadeDetail) GetBuyerOk() (*CommonAmsAccountPointer, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Buyer, true
}

// SetBuyer sets field value
func (o *AeAssetDealOfferMadeDetail) SetBuyer(v CommonAmsAccountPointer) {
	o.Buyer = v
}

// GetSaleDate returns the SaleDate field value
func (o *AeAssetDealOfferMadeDetail) GetSaleDate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SaleDate
}

// GetSaleDateOk returns a tuple with the SaleDate field value
// and a boolean to check if the value has been set.
func (o *AeAssetDealOfferMadeDetail) GetSaleDateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SaleDate, true
}

// SetSaleDate sets field value
func (o *AeAssetDealOfferMadeDetail) SetSaleDate(v string) {
	o.SaleDate = v
}

// GetLane returns the Lane field value
func (o *AeAssetDealOfferMadeDetail) GetLane() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Lane
}

// GetLaneOk returns a tuple with the Lane field value
// and a boolean to check if the value has been set.
func (o *AeAssetDealOfferMadeDetail) GetLaneOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lane, true
}

// SetLane sets field value
func (o *AeAssetDealOfferMadeDetail) SetLane(v string) {
	o.Lane = v
}

// GetLot returns the Lot field value
func (o *AeAssetDealOfferMadeDetail) GetLot() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Lot
}

// GetLotOk returns a tuple with the Lot field value
// and a boolean to check if the value has been set.
func (o *AeAssetDealOfferMadeDetail) GetLotOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Lot, true
}

// SetLot sets field value
func (o *AeAssetDealOfferMadeDetail) SetLot(v string) {
	o.Lot = v
}

// GetAmount returns the Amount field value
func (o *AeAssetDealOfferMadeDetail) GetAmount() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Amount
}

// GetAmountOk returns a tuple with the Amount field value
// and a boolean to check if the value has been set.
func (o *AeAssetDealOfferMadeDetail) GetAmountOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Amount, true
}

// SetAmount sets field value
func (o *AeAssetDealOfferMadeDetail) SetAmount(v float32) {
	o.Amount = v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *AeAssetDealOfferMadeDetail) GetUpdatedAt() time.Time {
	if o == nil || IsNil(o.UpdatedAt) {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAssetDealOfferMadeDetail) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.UpdatedAt) {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *AeAssetDealOfferMadeDetail) HasUpdatedAt() bool {
	if o != nil && !IsNil(o.UpdatedAt) {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *AeAssetDealOfferMadeDetail) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetInitiator returns the Initiator field value if set, zero value otherwise.
func (o *AeAssetDealOfferMadeDetail) GetInitiator() CommonInitiator {
	if o == nil || IsNil(o.Initiator) {
		var ret CommonInitiator
		return ret
	}
	return *o.Initiator
}

// GetInitiatorOk returns a tuple with the Initiator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAssetDealOfferMadeDetail) GetInitiatorOk() (*CommonInitiator, bool) {
	if o == nil || IsNil(o.Initiator) {
		return nil, false
	}
	return o.Initiator, true
}

// HasInitiator returns a boolean if a field has been set.
func (o *AeAssetDealOfferMadeDetail) HasInitiator() bool {
	if o != nil && !IsNil(o.Initiator) {
		return true
	}

	return false
}

// SetInitiator gets a reference to the given CommonInitiator and assigns it to the Initiator field.
func (o *AeAssetDealOfferMadeDetail) SetInitiator(v CommonInitiator) {
	o.Initiator = &v
}

func (o AeAssetDealOfferMadeDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AeAssetDealOfferMadeDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["auction-id"] = o.AuctionId
	if !IsNil(o.Asset) {
		toSerialize["asset"] = o.Asset
	}
	if !IsNil(o.DealId) {
		toSerialize["deal-id"] = o.DealId
	}
	toSerialize["vin"] = o.Vin
	toSerialize["stock"] = o.Stock
	toSerialize["seller"] = o.Seller
	toSerialize["buyer"] = o.Buyer
	toSerialize["sale-date"] = o.SaleDate
	toSerialize["lane"] = o.Lane
	toSerialize["lot"] = o.Lot
	toSerialize["amount"] = o.Amount
	if !IsNil(o.UpdatedAt) {
		toSerialize["updated-at"] = o.UpdatedAt
	}
	if !IsNil(o.Initiator) {
		toSerialize["initiator"] = o.Initiator
	}
	return toSerialize, nil
}

func (o *AeAssetDealOfferMadeDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"auction-id",
		"vin",
		"stock",
		"seller",
		"buyer",
		"sale-date",
		"lane",
		"lot",
		"amount",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAeAssetDealOfferMadeDetail := _AeAssetDealOfferMadeDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAeAssetDealOfferMadeDetail)

	if err != nil {
		return err
	}

	*o = AeAssetDealOfferMadeDetail(varAeAssetDealOfferMadeDetail)

	return err
}

type NullableAeAssetDealOfferMadeDetail struct {
	value *AeAssetDealOfferMadeDetail
	isSet bool
}

func (v NullableAeAssetDealOfferMadeDetail) Get() *AeAssetDealOfferMadeDetail {
	return v.value
}

func (v *NullableAeAssetDealOfferMadeDetail) Set(val *AeAssetDealOfferMadeDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableAeAssetDealOfferMadeDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableAeAssetDealOfferMadeDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAeAssetDealOfferMadeDetail(val *AeAssetDealOfferMadeDetail) *NullableAeAssetDealOfferMadeDetail {
	return &NullableAeAssetDealOfferMadeDetail{value: val, isSet: true}
}

func (v NullableAeAssetDealOfferMadeDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAeAssetDealOfferMadeDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


