/*
Edge Event Schemas

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package events

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AeAssetNegotiationOfferRejectedDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AeAssetNegotiationOfferRejectedDetail{}

// AeAssetNegotiationOfferRejectedDetail emitted by the negotiation service when an offer is rejected.
type AeAssetNegotiationOfferRejectedDetail struct {
	// Auction Edge unique identifier for an auction.
	AuctionId string `json:"auction-id"`
	// Uniquie identifier for a specific negotiation.
	NegotiationId string `json:"negotiation-id"`
	// unique identifier of the offer that is being rejected
	RejectedOfferId string `json:"rejected-offer-id"`
	Asset CommonAmsAssetPointer `json:"asset"`
	Offer AeAssetNegotiationOfferRejectedDetailOffer `json:"offer"`
	Initiator *CommonInitiator `json:"initiator,omitempty"`
}

type _AeAssetNegotiationOfferRejectedDetail AeAssetNegotiationOfferRejectedDetail

// NewAeAssetNegotiationOfferRejectedDetail instantiates a new AeAssetNegotiationOfferRejectedDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAeAssetNegotiationOfferRejectedDetail(auctionId string, negotiationId string, rejectedOfferId string, asset CommonAmsAssetPointer, offer AeAssetNegotiationOfferRejectedDetailOffer) *AeAssetNegotiationOfferRejectedDetail {
	this := AeAssetNegotiationOfferRejectedDetail{}
	this.AuctionId = auctionId
	this.NegotiationId = negotiationId
	this.RejectedOfferId = rejectedOfferId
	this.Asset = asset
	this.Offer = offer
	return &this
}

// NewAeAssetNegotiationOfferRejectedDetailWithDefaults instantiates a new AeAssetNegotiationOfferRejectedDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAeAssetNegotiationOfferRejectedDetailWithDefaults() *AeAssetNegotiationOfferRejectedDetail {
	this := AeAssetNegotiationOfferRejectedDetail{}
	return &this
}

// GetAuctionId returns the AuctionId field value
func (o *AeAssetNegotiationOfferRejectedDetail) GetAuctionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuctionId
}

// GetAuctionIdOk returns a tuple with the AuctionId field value
// and a boolean to check if the value has been set.
func (o *AeAssetNegotiationOfferRejectedDetail) GetAuctionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuctionId, true
}

// SetAuctionId sets field value
func (o *AeAssetNegotiationOfferRejectedDetail) SetAuctionId(v string) {
	o.AuctionId = v
}

// GetNegotiationId returns the NegotiationId field value
func (o *AeAssetNegotiationOfferRejectedDetail) GetNegotiationId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NegotiationId
}

// GetNegotiationIdOk returns a tuple with the NegotiationId field value
// and a boolean to check if the value has been set.
func (o *AeAssetNegotiationOfferRejectedDetail) GetNegotiationIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NegotiationId, true
}

// SetNegotiationId sets field value
func (o *AeAssetNegotiationOfferRejectedDetail) SetNegotiationId(v string) {
	o.NegotiationId = v
}

// GetRejectedOfferId returns the RejectedOfferId field value
func (o *AeAssetNegotiationOfferRejectedDetail) GetRejectedOfferId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RejectedOfferId
}

// GetRejectedOfferIdOk returns a tuple with the RejectedOfferId field value
// and a boolean to check if the value has been set.
func (o *AeAssetNegotiationOfferRejectedDetail) GetRejectedOfferIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RejectedOfferId, true
}

// SetRejectedOfferId sets field value
func (o *AeAssetNegotiationOfferRejectedDetail) SetRejectedOfferId(v string) {
	o.RejectedOfferId = v
}

// GetAsset returns the Asset field value
func (o *AeAssetNegotiationOfferRejectedDetail) GetAsset() CommonAmsAssetPointer {
	if o == nil {
		var ret CommonAmsAssetPointer
		return ret
	}

	return o.Asset
}

// GetAssetOk returns a tuple with the Asset field value
// and a boolean to check if the value has been set.
func (o *AeAssetNegotiationOfferRejectedDetail) GetAssetOk() (*CommonAmsAssetPointer, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Asset, true
}

// SetAsset sets field value
func (o *AeAssetNegotiationOfferRejectedDetail) SetAsset(v CommonAmsAssetPointer) {
	o.Asset = v
}

// GetOffer returns the Offer field value
func (o *AeAssetNegotiationOfferRejectedDetail) GetOffer() AeAssetNegotiationOfferRejectedDetailOffer {
	if o == nil {
		var ret AeAssetNegotiationOfferRejectedDetailOffer
		return ret
	}

	return o.Offer
}

// GetOfferOk returns a tuple with the Offer field value
// and a boolean to check if the value has been set.
func (o *AeAssetNegotiationOfferRejectedDetail) GetOfferOk() (*AeAssetNegotiationOfferRejectedDetailOffer, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Offer, true
}

// SetOffer sets field value
func (o *AeAssetNegotiationOfferRejectedDetail) SetOffer(v AeAssetNegotiationOfferRejectedDetailOffer) {
	o.Offer = v
}

// GetInitiator returns the Initiator field value if set, zero value otherwise.
func (o *AeAssetNegotiationOfferRejectedDetail) GetInitiator() CommonInitiator {
	if o == nil || IsNil(o.Initiator) {
		var ret CommonInitiator
		return ret
	}
	return *o.Initiator
}

// GetInitiatorOk returns a tuple with the Initiator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAssetNegotiationOfferRejectedDetail) GetInitiatorOk() (*CommonInitiator, bool) {
	if o == nil || IsNil(o.Initiator) {
		return nil, false
	}
	return o.Initiator, true
}

// HasInitiator returns a boolean if a field has been set.
func (o *AeAssetNegotiationOfferRejectedDetail) HasInitiator() bool {
	if o != nil && !IsNil(o.Initiator) {
		return true
	}

	return false
}

// SetInitiator gets a reference to the given CommonInitiator and assigns it to the Initiator field.
func (o *AeAssetNegotiationOfferRejectedDetail) SetInitiator(v CommonInitiator) {
	o.Initiator = &v
}

func (o AeAssetNegotiationOfferRejectedDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AeAssetNegotiationOfferRejectedDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["auction-id"] = o.AuctionId
	toSerialize["negotiation-id"] = o.NegotiationId
	toSerialize["rejected-offer-id"] = o.RejectedOfferId
	toSerialize["asset"] = o.Asset
	toSerialize["offer"] = o.Offer
	if !IsNil(o.Initiator) {
		toSerialize["initiator"] = o.Initiator
	}
	return toSerialize, nil
}

func (o *AeAssetNegotiationOfferRejectedDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"auction-id",
		"negotiation-id",
		"rejected-offer-id",
		"asset",
		"offer",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAeAssetNegotiationOfferRejectedDetail := _AeAssetNegotiationOfferRejectedDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAeAssetNegotiationOfferRejectedDetail)

	if err != nil {
		return err
	}

	*o = AeAssetNegotiationOfferRejectedDetail(varAeAssetNegotiationOfferRejectedDetail)

	return err
}

type NullableAeAssetNegotiationOfferRejectedDetail struct {
	value *AeAssetNegotiationOfferRejectedDetail
	isSet bool
}

func (v NullableAeAssetNegotiationOfferRejectedDetail) Get() *AeAssetNegotiationOfferRejectedDetail {
	return v.value
}

func (v *NullableAeAssetNegotiationOfferRejectedDetail) Set(val *AeAssetNegotiationOfferRejectedDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableAeAssetNegotiationOfferRejectedDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableAeAssetNegotiationOfferRejectedDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAeAssetNegotiationOfferRejectedDetail(val *AeAssetNegotiationOfferRejectedDetail) *NullableAeAssetNegotiationOfferRejectedDetail {
	return &NullableAeAssetNegotiationOfferRejectedDetail{value: val, isSet: true}
}

func (v NullableAeAssetNegotiationOfferRejectedDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAeAssetNegotiationOfferRejectedDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


