/*
Edge Event Schemas

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package events

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AeAssetLabelGeneratedDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AeAssetLabelGeneratedDetail{}

// AeAssetLabelGeneratedDetail Event fired when prints label request is successfully processed
type AeAssetLabelGeneratedDetail struct {
	// Auction Edge unique identifier for an auction.
	AuctionId string `json:"auction-id"`
	// Unique identifier for the request
	RequestId string `json:"request-id"`
	Asset *CommonAmsAssetPointer `json:"asset,omitempty"`
	// Source's unique identifier for asset
	AssetId string `json:"asset-id"`
	// The stock number of the asset.
	Stock string `json:"stock"`
	// The Vehicle Identification Number(VIN) of the asset.
	Vin string `json:"vin"`
	// Number of copies of the label to generate for asset
	Quantity float32 `json:"quantity"`
	LabelType LabelType `json:"label-type"`
	Initiator *CommonInitiator `json:"initiator,omitempty"`
}

type _AeAssetLabelGeneratedDetail AeAssetLabelGeneratedDetail

// NewAeAssetLabelGeneratedDetail instantiates a new AeAssetLabelGeneratedDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAeAssetLabelGeneratedDetail(auctionId string, requestId string, assetId string, stock string, vin string, quantity float32, labelType LabelType) *AeAssetLabelGeneratedDetail {
	this := AeAssetLabelGeneratedDetail{}
	this.AuctionId = auctionId
	this.RequestId = requestId
	this.AssetId = assetId
	this.Stock = stock
	this.Vin = vin
	this.Quantity = quantity
	this.LabelType = labelType
	return &this
}

// NewAeAssetLabelGeneratedDetailWithDefaults instantiates a new AeAssetLabelGeneratedDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAeAssetLabelGeneratedDetailWithDefaults() *AeAssetLabelGeneratedDetail {
	this := AeAssetLabelGeneratedDetail{}
	return &this
}

// GetAuctionId returns the AuctionId field value
func (o *AeAssetLabelGeneratedDetail) GetAuctionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuctionId
}

// GetAuctionIdOk returns a tuple with the AuctionId field value
// and a boolean to check if the value has been set.
func (o *AeAssetLabelGeneratedDetail) GetAuctionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuctionId, true
}

// SetAuctionId sets field value
func (o *AeAssetLabelGeneratedDetail) SetAuctionId(v string) {
	o.AuctionId = v
}

// GetRequestId returns the RequestId field value
func (o *AeAssetLabelGeneratedDetail) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *AeAssetLabelGeneratedDetail) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *AeAssetLabelGeneratedDetail) SetRequestId(v string) {
	o.RequestId = v
}

// GetAsset returns the Asset field value if set, zero value otherwise.
func (o *AeAssetLabelGeneratedDetail) GetAsset() CommonAmsAssetPointer {
	if o == nil || IsNil(o.Asset) {
		var ret CommonAmsAssetPointer
		return ret
	}
	return *o.Asset
}

// GetAssetOk returns a tuple with the Asset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAssetLabelGeneratedDetail) GetAssetOk() (*CommonAmsAssetPointer, bool) {
	if o == nil || IsNil(o.Asset) {
		return nil, false
	}
	return o.Asset, true
}

// HasAsset returns a boolean if a field has been set.
func (o *AeAssetLabelGeneratedDetail) HasAsset() bool {
	if o != nil && !IsNil(o.Asset) {
		return true
	}

	return false
}

// SetAsset gets a reference to the given CommonAmsAssetPointer and assigns it to the Asset field.
func (o *AeAssetLabelGeneratedDetail) SetAsset(v CommonAmsAssetPointer) {
	o.Asset = &v
}

// GetAssetId returns the AssetId field value
func (o *AeAssetLabelGeneratedDetail) GetAssetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AssetId
}

// GetAssetIdOk returns a tuple with the AssetId field value
// and a boolean to check if the value has been set.
func (o *AeAssetLabelGeneratedDetail) GetAssetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AssetId, true
}

// SetAssetId sets field value
func (o *AeAssetLabelGeneratedDetail) SetAssetId(v string) {
	o.AssetId = v
}

// GetStock returns the Stock field value
func (o *AeAssetLabelGeneratedDetail) GetStock() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Stock
}

// GetStockOk returns a tuple with the Stock field value
// and a boolean to check if the value has been set.
func (o *AeAssetLabelGeneratedDetail) GetStockOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Stock, true
}

// SetStock sets field value
func (o *AeAssetLabelGeneratedDetail) SetStock(v string) {
	o.Stock = v
}

// GetVin returns the Vin field value
func (o *AeAssetLabelGeneratedDetail) GetVin() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Vin
}

// GetVinOk returns a tuple with the Vin field value
// and a boolean to check if the value has been set.
func (o *AeAssetLabelGeneratedDetail) GetVinOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Vin, true
}

// SetVin sets field value
func (o *AeAssetLabelGeneratedDetail) SetVin(v string) {
	o.Vin = v
}

// GetQuantity returns the Quantity field value
func (o *AeAssetLabelGeneratedDetail) GetQuantity() float32 {
	if o == nil {
		var ret float32
		return ret
	}

	return o.Quantity
}

// GetQuantityOk returns a tuple with the Quantity field value
// and a boolean to check if the value has been set.
func (o *AeAssetLabelGeneratedDetail) GetQuantityOk() (*float32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Quantity, true
}

// SetQuantity sets field value
func (o *AeAssetLabelGeneratedDetail) SetQuantity(v float32) {
	o.Quantity = v
}

// GetLabelType returns the LabelType field value
func (o *AeAssetLabelGeneratedDetail) GetLabelType() LabelType {
	if o == nil {
		var ret LabelType
		return ret
	}

	return o.LabelType
}

// GetLabelTypeOk returns a tuple with the LabelType field value
// and a boolean to check if the value has been set.
func (o *AeAssetLabelGeneratedDetail) GetLabelTypeOk() (*LabelType, bool) {
	if o == nil {
		return nil, false
	}
	return &o.LabelType, true
}

// SetLabelType sets field value
func (o *AeAssetLabelGeneratedDetail) SetLabelType(v LabelType) {
	o.LabelType = v
}

// GetInitiator returns the Initiator field value if set, zero value otherwise.
func (o *AeAssetLabelGeneratedDetail) GetInitiator() CommonInitiator {
	if o == nil || IsNil(o.Initiator) {
		var ret CommonInitiator
		return ret
	}
	return *o.Initiator
}

// GetInitiatorOk returns a tuple with the Initiator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAssetLabelGeneratedDetail) GetInitiatorOk() (*CommonInitiator, bool) {
	if o == nil || IsNil(o.Initiator) {
		return nil, false
	}
	return o.Initiator, true
}

// HasInitiator returns a boolean if a field has been set.
func (o *AeAssetLabelGeneratedDetail) HasInitiator() bool {
	if o != nil && !IsNil(o.Initiator) {
		return true
	}

	return false
}

// SetInitiator gets a reference to the given CommonInitiator and assigns it to the Initiator field.
func (o *AeAssetLabelGeneratedDetail) SetInitiator(v CommonInitiator) {
	o.Initiator = &v
}

func (o AeAssetLabelGeneratedDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AeAssetLabelGeneratedDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["auction-id"] = o.AuctionId
	toSerialize["request-id"] = o.RequestId
	if !IsNil(o.Asset) {
		toSerialize["asset"] = o.Asset
	}
	toSerialize["asset-id"] = o.AssetId
	toSerialize["stock"] = o.Stock
	toSerialize["vin"] = o.Vin
	toSerialize["quantity"] = o.Quantity
	toSerialize["label-type"] = o.LabelType
	if !IsNil(o.Initiator) {
		toSerialize["initiator"] = o.Initiator
	}
	return toSerialize, nil
}

func (o *AeAssetLabelGeneratedDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"auction-id",
		"request-id",
		"asset-id",
		"stock",
		"vin",
		"quantity",
		"label-type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAeAssetLabelGeneratedDetail := _AeAssetLabelGeneratedDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAeAssetLabelGeneratedDetail)

	if err != nil {
		return err
	}

	*o = AeAssetLabelGeneratedDetail(varAeAssetLabelGeneratedDetail)

	return err
}

type NullableAeAssetLabelGeneratedDetail struct {
	value *AeAssetLabelGeneratedDetail
	isSet bool
}

func (v NullableAeAssetLabelGeneratedDetail) Get() *AeAssetLabelGeneratedDetail {
	return v.value
}

func (v *NullableAeAssetLabelGeneratedDetail) Set(val *AeAssetLabelGeneratedDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableAeAssetLabelGeneratedDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableAeAssetLabelGeneratedDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAeAssetLabelGeneratedDetail(val *AeAssetLabelGeneratedDetail) *NullableAeAssetLabelGeneratedDetail {
	return &NullableAeAssetLabelGeneratedDetail{value: val, isSet: true}
}

func (v NullableAeAssetLabelGeneratedDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAeAssetLabelGeneratedDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


