/*
Edge Event Schemas

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package events

import (
	"encoding/json"
	"fmt"
)

// checks if the AeAssetDealPaymentStatusChangedDetailDeal type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AeAssetDealPaymentStatusChangedDetailDeal{}

// AeAssetDealPaymentStatusChangedDetailDeal struct for AeAssetDealPaymentStatusChangedDetailDeal
type AeAssetDealPaymentStatusChangedDetailDeal struct {
	// Unique id for a deal
	Id string `json:"id"`
	Payment AeAssetDealPaymentStatusChangedDetailDealPayment `json:"payment"`
	AdditionalProperties map[string]interface{}
}

type _AeAssetDealPaymentStatusChangedDetailDeal AeAssetDealPaymentStatusChangedDetailDeal

// NewAeAssetDealPaymentStatusChangedDetailDeal instantiates a new AeAssetDealPaymentStatusChangedDetailDeal object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAeAssetDealPaymentStatusChangedDetailDeal(id string, payment AeAssetDealPaymentStatusChangedDetailDealPayment) *AeAssetDealPaymentStatusChangedDetailDeal {
	this := AeAssetDealPaymentStatusChangedDetailDeal{}
	this.Id = id
	this.Payment = payment
	return &this
}

// NewAeAssetDealPaymentStatusChangedDetailDealWithDefaults instantiates a new AeAssetDealPaymentStatusChangedDetailDeal object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAeAssetDealPaymentStatusChangedDetailDealWithDefaults() *AeAssetDealPaymentStatusChangedDetailDeal {
	this := AeAssetDealPaymentStatusChangedDetailDeal{}
	return &this
}

// GetId returns the Id field value
func (o *AeAssetDealPaymentStatusChangedDetailDeal) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *AeAssetDealPaymentStatusChangedDetailDeal) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *AeAssetDealPaymentStatusChangedDetailDeal) SetId(v string) {
	o.Id = v
}

// GetPayment returns the Payment field value
func (o *AeAssetDealPaymentStatusChangedDetailDeal) GetPayment() AeAssetDealPaymentStatusChangedDetailDealPayment {
	if o == nil {
		var ret AeAssetDealPaymentStatusChangedDetailDealPayment
		return ret
	}

	return o.Payment
}

// GetPaymentOk returns a tuple with the Payment field value
// and a boolean to check if the value has been set.
func (o *AeAssetDealPaymentStatusChangedDetailDeal) GetPaymentOk() (*AeAssetDealPaymentStatusChangedDetailDealPayment, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Payment, true
}

// SetPayment sets field value
func (o *AeAssetDealPaymentStatusChangedDetailDeal) SetPayment(v AeAssetDealPaymentStatusChangedDetailDealPayment) {
	o.Payment = v
}

func (o AeAssetDealPaymentStatusChangedDetailDeal) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AeAssetDealPaymentStatusChangedDetailDeal) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["id"] = o.Id
	toSerialize["payment"] = o.Payment

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *AeAssetDealPaymentStatusChangedDetailDeal) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"id",
		"payment",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAeAssetDealPaymentStatusChangedDetailDeal := _AeAssetDealPaymentStatusChangedDetailDeal{}

	err = json.Unmarshal(data, &varAeAssetDealPaymentStatusChangedDetailDeal)

	if err != nil {
		return err
	}

	*o = AeAssetDealPaymentStatusChangedDetailDeal(varAeAssetDealPaymentStatusChangedDetailDeal)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "id")
		delete(additionalProperties, "payment")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableAeAssetDealPaymentStatusChangedDetailDeal struct {
	value *AeAssetDealPaymentStatusChangedDetailDeal
	isSet bool
}

func (v NullableAeAssetDealPaymentStatusChangedDetailDeal) Get() *AeAssetDealPaymentStatusChangedDetailDeal {
	return v.value
}

func (v *NullableAeAssetDealPaymentStatusChangedDetailDeal) Set(val *AeAssetDealPaymentStatusChangedDetailDeal) {
	v.value = val
	v.isSet = true
}

func (v NullableAeAssetDealPaymentStatusChangedDetailDeal) IsSet() bool {
	return v.isSet
}

func (v *NullableAeAssetDealPaymentStatusChangedDetailDeal) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAeAssetDealPaymentStatusChangedDetailDeal(val *AeAssetDealPaymentStatusChangedDetailDeal) *NullableAeAssetDealPaymentStatusChangedDetailDeal {
	return &NullableAeAssetDealPaymentStatusChangedDetailDeal{value: val, isSet: true}
}

func (v NullableAeAssetDealPaymentStatusChangedDetailDeal) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAeAssetDealPaymentStatusChangedDetailDeal) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


