/*
Edge Event Schemas

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package events

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AeUserInfoAdvisoryDataSourceUpdatedDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AeUserInfoAdvisoryDataSourceUpdatedDetail{}

// AeUserInfoAdvisoryDataSourceUpdatedDetail Advisory message for user-info
type AeUserInfoAdvisoryDataSourceUpdatedDetail struct {
	Version string `json:"version"`
	Bucket AeUserInfoAdvisoryDataSourceUpdatedDetailBucket `json:"bucket"`
	Object AeUserInfoAdvisoryDataSourceUpdatedDetailObject `json:"object"`
	RequestId string `json:"request-id"`
	Requester string `json:"requester"`
	SourceIpAddress string `json:"source-ip-address"`
	Reason string `json:"reason"`
	Initiator *CommonInitiator `json:"initiator,omitempty"`
}

type _AeUserInfoAdvisoryDataSourceUpdatedDetail AeUserInfoAdvisoryDataSourceUpdatedDetail

// NewAeUserInfoAdvisoryDataSourceUpdatedDetail instantiates a new AeUserInfoAdvisoryDataSourceUpdatedDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAeUserInfoAdvisoryDataSourceUpdatedDetail(version string, bucket AeUserInfoAdvisoryDataSourceUpdatedDetailBucket, object AeUserInfoAdvisoryDataSourceUpdatedDetailObject, requestId string, requester string, sourceIpAddress string, reason string) *AeUserInfoAdvisoryDataSourceUpdatedDetail {
	this := AeUserInfoAdvisoryDataSourceUpdatedDetail{}
	this.Version = version
	this.Bucket = bucket
	this.Object = object
	this.RequestId = requestId
	this.Requester = requester
	this.SourceIpAddress = sourceIpAddress
	this.Reason = reason
	return &this
}

// NewAeUserInfoAdvisoryDataSourceUpdatedDetailWithDefaults instantiates a new AeUserInfoAdvisoryDataSourceUpdatedDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAeUserInfoAdvisoryDataSourceUpdatedDetailWithDefaults() *AeUserInfoAdvisoryDataSourceUpdatedDetail {
	this := AeUserInfoAdvisoryDataSourceUpdatedDetail{}
	return &this
}

// GetVersion returns the Version field value
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetail) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetail) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetail) SetVersion(v string) {
	o.Version = v
}

// GetBucket returns the Bucket field value
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetail) GetBucket() AeUserInfoAdvisoryDataSourceUpdatedDetailBucket {
	if o == nil {
		var ret AeUserInfoAdvisoryDataSourceUpdatedDetailBucket
		return ret
	}

	return o.Bucket
}

// GetBucketOk returns a tuple with the Bucket field value
// and a boolean to check if the value has been set.
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetail) GetBucketOk() (*AeUserInfoAdvisoryDataSourceUpdatedDetailBucket, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Bucket, true
}

// SetBucket sets field value
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetail) SetBucket(v AeUserInfoAdvisoryDataSourceUpdatedDetailBucket) {
	o.Bucket = v
}

// GetObject returns the Object field value
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetail) GetObject() AeUserInfoAdvisoryDataSourceUpdatedDetailObject {
	if o == nil {
		var ret AeUserInfoAdvisoryDataSourceUpdatedDetailObject
		return ret
	}

	return o.Object
}

// GetObjectOk returns a tuple with the Object field value
// and a boolean to check if the value has been set.
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetail) GetObjectOk() (*AeUserInfoAdvisoryDataSourceUpdatedDetailObject, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Object, true
}

// SetObject sets field value
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetail) SetObject(v AeUserInfoAdvisoryDataSourceUpdatedDetailObject) {
	o.Object = v
}

// GetRequestId returns the RequestId field value
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetail) GetRequestId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.RequestId
}

// GetRequestIdOk returns a tuple with the RequestId field value
// and a boolean to check if the value has been set.
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetail) GetRequestIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RequestId, true
}

// SetRequestId sets field value
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetail) SetRequestId(v string) {
	o.RequestId = v
}

// GetRequester returns the Requester field value
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetail) GetRequester() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Requester
}

// GetRequesterOk returns a tuple with the Requester field value
// and a boolean to check if the value has been set.
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetail) GetRequesterOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Requester, true
}

// SetRequester sets field value
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetail) SetRequester(v string) {
	o.Requester = v
}

// GetSourceIpAddress returns the SourceIpAddress field value
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetail) GetSourceIpAddress() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.SourceIpAddress
}

// GetSourceIpAddressOk returns a tuple with the SourceIpAddress field value
// and a boolean to check if the value has been set.
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetail) GetSourceIpAddressOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.SourceIpAddress, true
}

// SetSourceIpAddress sets field value
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetail) SetSourceIpAddress(v string) {
	o.SourceIpAddress = v
}

// GetReason returns the Reason field value
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetail) GetReason() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Reason
}

// GetReasonOk returns a tuple with the Reason field value
// and a boolean to check if the value has been set.
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetail) GetReasonOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Reason, true
}

// SetReason sets field value
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetail) SetReason(v string) {
	o.Reason = v
}

// GetInitiator returns the Initiator field value if set, zero value otherwise.
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetail) GetInitiator() CommonInitiator {
	if o == nil || IsNil(o.Initiator) {
		var ret CommonInitiator
		return ret
	}
	return *o.Initiator
}

// GetInitiatorOk returns a tuple with the Initiator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetail) GetInitiatorOk() (*CommonInitiator, bool) {
	if o == nil || IsNil(o.Initiator) {
		return nil, false
	}
	return o.Initiator, true
}

// HasInitiator returns a boolean if a field has been set.
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetail) HasInitiator() bool {
	if o != nil && !IsNil(o.Initiator) {
		return true
	}

	return false
}

// SetInitiator gets a reference to the given CommonInitiator and assigns it to the Initiator field.
func (o *AeUserInfoAdvisoryDataSourceUpdatedDetail) SetInitiator(v CommonInitiator) {
	o.Initiator = &v
}

func (o AeUserInfoAdvisoryDataSourceUpdatedDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AeUserInfoAdvisoryDataSourceUpdatedDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["version"] = o.Version
	toSerialize["bucket"] = o.Bucket
	toSerialize["object"] = o.Object
	toSerialize["request-id"] = o.RequestId
	toSerialize["requester"] = o.Requester
	toSerialize["source-ip-address"] = o.SourceIpAddress
	toSerialize["reason"] = o.Reason
	if !IsNil(o.Initiator) {
		toSerialize["initiator"] = o.Initiator
	}
	return toSerialize, nil
}

func (o *AeUserInfoAdvisoryDataSourceUpdatedDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"version",
		"bucket",
		"object",
		"request-id",
		"requester",
		"source-ip-address",
		"reason",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAeUserInfoAdvisoryDataSourceUpdatedDetail := _AeUserInfoAdvisoryDataSourceUpdatedDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAeUserInfoAdvisoryDataSourceUpdatedDetail)

	if err != nil {
		return err
	}

	*o = AeUserInfoAdvisoryDataSourceUpdatedDetail(varAeUserInfoAdvisoryDataSourceUpdatedDetail)

	return err
}

type NullableAeUserInfoAdvisoryDataSourceUpdatedDetail struct {
	value *AeUserInfoAdvisoryDataSourceUpdatedDetail
	isSet bool
}

func (v NullableAeUserInfoAdvisoryDataSourceUpdatedDetail) Get() *AeUserInfoAdvisoryDataSourceUpdatedDetail {
	return v.value
}

func (v *NullableAeUserInfoAdvisoryDataSourceUpdatedDetail) Set(val *AeUserInfoAdvisoryDataSourceUpdatedDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableAeUserInfoAdvisoryDataSourceUpdatedDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableAeUserInfoAdvisoryDataSourceUpdatedDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAeUserInfoAdvisoryDataSourceUpdatedDetail(val *AeUserInfoAdvisoryDataSourceUpdatedDetail) *NullableAeUserInfoAdvisoryDataSourceUpdatedDetail {
	return &NullableAeUserInfoAdvisoryDataSourceUpdatedDetail{value: val, isSet: true}
}

func (v NullableAeUserInfoAdvisoryDataSourceUpdatedDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAeUserInfoAdvisoryDataSourceUpdatedDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


