/*
Edge Event Schemas

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package events

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AeAccountRepresentativePayerDeauthorizedDetail type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AeAccountRepresentativePayerDeauthorizedDetail{}

// AeAccountRepresentativePayerDeauthorizedDetail A representative has been de-authorized to pay for an account
type AeAccountRepresentativePayerDeauthorizedDetail struct {
	// Auction Edge unique identifier for an auction.
	AuctionId string `json:"auction-id"`
	Account CommonAmsAccountPointer `json:"account"`
	// Deprecated
	RepAccount CommonAmsRepPointer `json:"rep-account"`
	Initiator *CommonInitiator `json:"initiator,omitempty"`
}

type _AeAccountRepresentativePayerDeauthorizedDetail AeAccountRepresentativePayerDeauthorizedDetail

// NewAeAccountRepresentativePayerDeauthorizedDetail instantiates a new AeAccountRepresentativePayerDeauthorizedDetail object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAeAccountRepresentativePayerDeauthorizedDetail(auctionId string, account CommonAmsAccountPointer, repAccount CommonAmsRepPointer) *AeAccountRepresentativePayerDeauthorizedDetail {
	this := AeAccountRepresentativePayerDeauthorizedDetail{}
	this.AuctionId = auctionId
	this.Account = account
	this.RepAccount = repAccount
	return &this
}

// NewAeAccountRepresentativePayerDeauthorizedDetailWithDefaults instantiates a new AeAccountRepresentativePayerDeauthorizedDetail object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAeAccountRepresentativePayerDeauthorizedDetailWithDefaults() *AeAccountRepresentativePayerDeauthorizedDetail {
	this := AeAccountRepresentativePayerDeauthorizedDetail{}
	return &this
}

// GetAuctionId returns the AuctionId field value
func (o *AeAccountRepresentativePayerDeauthorizedDetail) GetAuctionId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.AuctionId
}

// GetAuctionIdOk returns a tuple with the AuctionId field value
// and a boolean to check if the value has been set.
func (o *AeAccountRepresentativePayerDeauthorizedDetail) GetAuctionIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AuctionId, true
}

// SetAuctionId sets field value
func (o *AeAccountRepresentativePayerDeauthorizedDetail) SetAuctionId(v string) {
	o.AuctionId = v
}

// GetAccount returns the Account field value
func (o *AeAccountRepresentativePayerDeauthorizedDetail) GetAccount() CommonAmsAccountPointer {
	if o == nil {
		var ret CommonAmsAccountPointer
		return ret
	}

	return o.Account
}

// GetAccountOk returns a tuple with the Account field value
// and a boolean to check if the value has been set.
func (o *AeAccountRepresentativePayerDeauthorizedDetail) GetAccountOk() (*CommonAmsAccountPointer, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Account, true
}

// SetAccount sets field value
func (o *AeAccountRepresentativePayerDeauthorizedDetail) SetAccount(v CommonAmsAccountPointer) {
	o.Account = v
}

// GetRepAccount returns the RepAccount field value
// Deprecated
func (o *AeAccountRepresentativePayerDeauthorizedDetail) GetRepAccount() CommonAmsRepPointer {
	if o == nil {
		var ret CommonAmsRepPointer
		return ret
	}

	return o.RepAccount
}

// GetRepAccountOk returns a tuple with the RepAccount field value
// and a boolean to check if the value has been set.
// Deprecated
func (o *AeAccountRepresentativePayerDeauthorizedDetail) GetRepAccountOk() (*CommonAmsRepPointer, bool) {
	if o == nil {
		return nil, false
	}
	return &o.RepAccount, true
}

// SetRepAccount sets field value
// Deprecated
func (o *AeAccountRepresentativePayerDeauthorizedDetail) SetRepAccount(v CommonAmsRepPointer) {
	o.RepAccount = v
}

// GetInitiator returns the Initiator field value if set, zero value otherwise.
func (o *AeAccountRepresentativePayerDeauthorizedDetail) GetInitiator() CommonInitiator {
	if o == nil || IsNil(o.Initiator) {
		var ret CommonInitiator
		return ret
	}
	return *o.Initiator
}

// GetInitiatorOk returns a tuple with the Initiator field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AeAccountRepresentativePayerDeauthorizedDetail) GetInitiatorOk() (*CommonInitiator, bool) {
	if o == nil || IsNil(o.Initiator) {
		return nil, false
	}
	return o.Initiator, true
}

// HasInitiator returns a boolean if a field has been set.
func (o *AeAccountRepresentativePayerDeauthorizedDetail) HasInitiator() bool {
	if o != nil && !IsNil(o.Initiator) {
		return true
	}

	return false
}

// SetInitiator gets a reference to the given CommonInitiator and assigns it to the Initiator field.
func (o *AeAccountRepresentativePayerDeauthorizedDetail) SetInitiator(v CommonInitiator) {
	o.Initiator = &v
}

func (o AeAccountRepresentativePayerDeauthorizedDetail) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AeAccountRepresentativePayerDeauthorizedDetail) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["auction-id"] = o.AuctionId
	toSerialize["account"] = o.Account
	toSerialize["rep-account"] = o.RepAccount
	if !IsNil(o.Initiator) {
		toSerialize["initiator"] = o.Initiator
	}
	return toSerialize, nil
}

func (o *AeAccountRepresentativePayerDeauthorizedDetail) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"auction-id",
		"account",
		"rep-account",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAeAccountRepresentativePayerDeauthorizedDetail := _AeAccountRepresentativePayerDeauthorizedDetail{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAeAccountRepresentativePayerDeauthorizedDetail)

	if err != nil {
		return err
	}

	*o = AeAccountRepresentativePayerDeauthorizedDetail(varAeAccountRepresentativePayerDeauthorizedDetail)

	return err
}

type NullableAeAccountRepresentativePayerDeauthorizedDetail struct {
	value *AeAccountRepresentativePayerDeauthorizedDetail
	isSet bool
}

func (v NullableAeAccountRepresentativePayerDeauthorizedDetail) Get() *AeAccountRepresentativePayerDeauthorizedDetail {
	return v.value
}

func (v *NullableAeAccountRepresentativePayerDeauthorizedDetail) Set(val *AeAccountRepresentativePayerDeauthorizedDetail) {
	v.value = val
	v.isSet = true
}

func (v NullableAeAccountRepresentativePayerDeauthorizedDetail) IsSet() bool {
	return v.isSet
}

func (v *NullableAeAccountRepresentativePayerDeauthorizedDetail) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAeAccountRepresentativePayerDeauthorizedDetail(val *AeAccountRepresentativePayerDeauthorizedDetail) *NullableAeAccountRepresentativePayerDeauthorizedDetail {
	return &NullableAeAccountRepresentativePayerDeauthorizedDetail{value: val, isSet: true}
}

func (v NullableAeAccountRepresentativePayerDeauthorizedDetail) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAeAccountRepresentativePayerDeauthorizedDetail) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


